{
 "title": "TERANODE Block Assembly",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "grouping_interval",
    "label": "Grouping Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(propagation_transactions_size_sum,instance)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(propagation_transactions_size_count,namespace)"
    }
   },
   { "name": "srvc", "label": "Service", "query": { "query": "label_values(service)" } },
   { "name": "prometheus", "label": "Prometheus", "query": "prometheus" },
   { "name": "subsystem", "label": "Subsystem", "query": { "query": "label_values(subsystem)" } }
  ]
 },
 "panels": [
  {
   "title": "Validator Processed Transactions",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(increase(teranode_validator_transactions_validate_total_count{instance=~\"$instance\",service=~\"$srvc\",namespace=~\"$namespace\",subsystem=~\"$subsystem\"}[$grouping_interval])) by (service) / 60  >0",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Percentiles -> BA",
   "type": "stat",
   "description": "Average across all nodes counted into buckets from 0 to 2^16",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg by (namespace) (histogram_quantile(0.95, (avg(rate(teranode_validator_transactions_validate_total_bucket{instance=~\"$instance\",service=~\"$srvc\",namespace=~\"$namespace\",subsystem=~\"$subsystem\"}[$grouping_interval])))))",
     "legendFormat": "p95 us "
    },
    {
     "expr": "avg by (namespace) (histogram_quantile(0.99, (avg(rate(teranode_validator_transactions_validate_total_bucket{instance=~\"$instance\",service=~\"$srvc\",namespace=~\"$namespace\",subsystem=~\"$subsystem\"}[$grouping_interval])))))",
     "legendFormat": "p99 us"
    },
    {
     "expr": "avg by (namespace) (histogram_quantile(0.999, avg(rate(teranode_validator_transactions_validate_total_bucket{instance=~\"$instance\",service=~\"$srvc\",namespace=~\"$namespace\"}[$grouping_interval]))))\n",
     "legendFormat": "p99.9 us"
    }
   ]
  },
  {
   "title": "Add TX Latency",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 10 },
   "targets": [
    {
     "expr": "sum(increase(teranode_blockassembly_add_tx_bucket{instance=~\"$instance\",service=~\"$srvc\",namespace=~\"$namespace\",subsystem=~\"$subsystem\"}[$grouping_interval])) by (le)",
     "legendFormat": "{{ le }}us"
    }
   ]
  },
  {
   "title": "Percentiles -> BA",
   "type": "stat",
   "description": "Average across all nodes counted into buckets from 0 to 2^16",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg by (namespace) (histogram_quantile(0.95, (avg(rate(teranode_validator_transactions_validate_total_bucket{instance=~\"$instance\",service=~\"$srvc\",namespace=~\"$namespace\",subsystem=~\"$subsystem\"}[$grouping_interval])))))",
     "legendFormat": "p95 us"
    },
    {
     "expr": "avg by (namespace) (histogram_quantile(0.99, avg(rate(teranode_validator_transactions_validate_total_bucket{instance=~\"$instance\",service=~\"$srvc\",namespace=~\"$namespace\",subsystem=~\"$subsystem\"}[$grouping_interval]))))\n",
     "legendFormat": "p99 us"
    },
    {
     "expr": "avg by (namespace) (histogram_quantile(0.999, (avg(rate(teranode_validator_transactions_validate_total_bucket{instance=~\"$instance\",service=~\"$srvc\",namespace=~\"$namespace\",subsystem=~\"$subsystem\"}[$grouping_interval])))))",
     "legendFormat": "p99.9 us"
    }
   ]
  },
  {
   "title": "Get Mining Candidate Latency",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 19 },
   "targets": [
    {
     "expr": "sum(increase(teranode_blockassembly_get_mining_candidate_duration_bucket{instance=~\"$instance\",service=~\"$srvc\",namespace=~\"$namespace\",subsystem=~\"$subsystem\"}[$grouping_interval])) by (le)",
     "legendFormat": "{{ le }}us"
    }
   ]
  },
  {
   "title": "Submit Mining Solution Latency",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 28 },
   "targets": [
    {
     "expr": "sum(increase(teranode_blockassembly_submit_mining_solution_bucket{instance=~\"$instance\",service=~\"$srvc\",namespace=~\"$namespace\",subsystem=~\"$subsystem\"}[$grouping_interval])) by (le)",
     "legendFormat": "{{ le }}us"
    }
   ]
  },
  {
   "title": "Move Up Latency",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 37 },
   "targets": [
    {
     "expr": "sum(increase(teranode_subtreeprocessor_move_up_duration_bucket{instance=~\"$instance\",service=~\"$srvc\",namespace=~\"$namespace\",subsystem=~\"$subsystem\"}[$grouping_interval])) by (le)",
     "legendFormat": "{{ le }}us"
    }
   ]
  },
  {
   "title": "Move Down Latency",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 46 },
   "targets": [
    {
     "expr": "sum(increase(teranode_subtreeprocessor_move_down_duration_bucket{instance=~\"$instance\",service=~\"$srvc\",namespace=~\"$namespace\",subsystem=~\"$subsystem\"}[$grouping_interval])) by (le)",
     "legendFormat": "{{ le }}us"
    }
   ]
  },
  {
   "title": "Coinbase TX Latency",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 55 },
   "targets": [
    {
     "expr": "sum(increase(teranode_subtreeprocessor_process_coinbase_tx_duration_bucket{instance=~\"$instance\",service=~\"$srvc\",namespace=~\"$namespace\",subsystem=~\"$subsystem\"}[$grouping_interval])) by (le)",
     "legendFormat": "{{ le }}us"
    }
   ]
  },
  {
   "title": "Transaction Map Latency",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 64 },
   "targets": [
    {
     "expr": "sum(increase(teranode_subtreeprocessor_transaction_map_duration_bucket{instance=~\"$instance\",service=~\"$srvc\",namespace=~\"$namespace\",subsystem=~\"$subsystem\"}[$grouping_interval])) by (le)",
     "legendFormat": "{{ le }}us"
    }
   ]
  }
 ]
}