linters-settings:
  forbidigo:
    forbid:
      # Optional message that gets included in error reports.
      - p: ^fmt\.Errorf.*$
        msg: use of fmt.Errorf is deprecated, please use errors.New

linters:
  enable:
    - gosec
    - errcheck
    - forbidigo

issues:
  exclude-rules:
    - path: services/legacy
      linters:
        - govet
        - staticcheck
        - unused
        - errcheck
        - ineffassign
        - forbidigo
