linters-settings:
  forbidigo:
    forbid:
      # Optional message that gets included in error reports.
      - p: ^fmt\.Errorf.*$
        msg: use of fmt.Errorf is deprecated, please use errors.New

linters:
  enable:
    - gosec
    - errcheck
    - forbidigo

issues:
  # exclude-dirs:
  #   - services/legacy/bsvutil
  #   - services/legacy/wire
  exclude:
    - "G108: Profiling endpoint is automatically exposed on /debug/pprof"
    - "G601: Implicit memory aliasing in for loop."

  exclude-rules:
    - path: services/legacy
      linters:
        - govet
        - staticcheck
        - unused
        - errcheck
        - ineffassign
        - forbidigo

    - path: services/rpc
      linters:
        - govet
        - staticcheck
        - unused
        - errcheck
        - ineffassign
        - forbidigo
