linters-settings:
  gci:
    sections:
      - standard # Standard section: captures all standard packages.
      - default # Default section: contains all imports that could not be matched to another section type.
      - prefix(github.com/org/project) # Custom section: groups all imports with the specified Prefix.
      - blank # Blank section: contains all blank imports. This section is not present unless explicitly enabled.
      - dot # Dot section: contains all dot imports. This section is not present unless explicitly enabled.
      - alias # Alias section: contains all alias imports. This section is not present unless explicitly enabled.
      - localmodule # Local module section: contains all local packages. This section is not present unless explicitly enabled.
  depguard:
    rules:
      main:
        deny:
          - pkg: "errors"
            desc: Should be replaced by standard lib errors package
  forbidigo:
    forbid:
      - p: ^fmt\.Errorf.*$
        msg: use of fmt.Errorf is deprecated, please use errors.New

linters:
  enable:
    - asciicheck
    - depguard
    - errcheck
    - forbidigo
    - gocognit
    - goconst
    - gocritic
    - gci
    - goimports
    - gosec
    - misspell
    - prealloc
    - stylecheck
    - unconvert
    - whitespace
    - wsl

issues:
  exclude-rules:
    - path: services/legacy
      linters:
        - govet
        - staticcheck
        - unused
        - errcheck
        - ineffassign
        - forbidigo
        - depguard
    - path: errors
      linters:
        - depguard
        - forbidigo
