linters:
  enable:
    - gosec
    - errcheck

issues:
  # exclude-dirs:
  #   - services/legacy/bsvutil
  #   - services/legacy/wire

  exclude-rules:
    - path: services/legacy
      linters:
        - govet
        - staticcheck
        - unused
        - errcheck
        - ineffassign

    - path: services/rpc
      linters:
        - govet
        - staticcheck
        - unused
        - errcheck
        - ineffassign
