linters:
  enable:
    - gosec
    - errcheck

issues:
  # exclude-dirs:
  #   - services/legacy/bsvutil
  #   - services/legacy/wire
  exclude:
    - "G108: Profiling endpoint is automatically exposed on /debug/pprof"
    - "G601: Implicit memory aliasing in for loop."

  exclude-rules:
    - path: services/legacy
      linters:
        - govet
        - staticcheck
        - unused
        - errcheck
        - ineffassign

    - path: services/rpc
      linters:
        - govet
        - staticcheck
        - unused
        - errcheck
        - ineffassign
