linters-settings:
  depguard:
    rules:
      main:
        deny:
          - pkg: "errors"
            desc: Should be replaced by standard lib errors package
  forbidigo:
    forbid:
      - p: ^fmt\.Errorf.*$
        msg: use of fmt.Errorf is deprecated, please use errors.New

linters:
  enable:
    - gosec
    - errcheck
    - forbidigo
    - depguard

issues:
  exclude-rules:
    - path: services/legacy
      linters:
        - govet
        - staticcheck
        - unused
        - errcheck
        - ineffassign
        - forbidigo
        - depguard
    - path: errors
      linters:
        - depguard
        - forbidigo
