version: '3.8'
# runs on a 16GB macbook with 12GB allocated to Docker
# uses a single postgres, single kafka, no aerospike and a single tx-blaster

x-ubsv-base:
  mem_limit: 2g
  environment:
    GOGC: "50"

x-common-env: &common-env
  KAFKA_HEAP_OPTS: "-Xms256M -Xmx256M"
  KAFKA_BUFFER_MEMORY: "33554432"  # Example buffer.memory setting (32MB)
  KAFKA_BATCH_SIZE: "8096"        # Example batch.size setting (16KB)

x-aerospike-base: &aerospike-base
  mem_limit: 1024m

services:
  postgres:
    mem_limit: 128m
    volumes:
      - ./deploy/dev/postgres-update-config.sh:/docker-entrypoint-initdb.d/postgres-update-config.sh
      - ./scripts/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
  ubsv-1:
    depends_on:
      - aerospike-1
    entrypoint: ["/app/wait.sh", "aerospike-1", "3000", "2", "--", "/app/wait.sh", "postgres", "5432", "0", "--", "/app/wait.sh", "kafka-shared", "9092", "0", "--", "/app/ubsv.run", "-miner=1", "-coinbase=1"]

  ubsv-2:
    depends_on:
      - aerospike-2
    entrypoint: ["/app/wait.sh", "aerospike-2", "3000", "2", "--", "/app/wait.sh", "postgres", "5432", "0", "--", "/app/wait.sh", "kafka-shared", "9092", "0", "--", "/app/ubsv.run", "-miner=1", "-coinbase=0"]

  ubsv-3:
    depends_on:
      - aerospike-3
    entrypoint: ["/app/wait.sh", "aerospike-3", "3000", "2", "--", "/app/wait.sh", "postgres", "5432", "0", "--", "/app/wait.sh", "kafka-shared", "9092", "0", "--", "/app/ubsv.run", "-miner=1", "-coinbase=0"]
