version: '3.8'

# Define a common base configuration for ubsv nodes
x-ubsv-base:
  &ubsv-base
  image: taal/ubsv:latest
  depends_on:
    - postgres
  build:
    context: .
    dockerfile: local.Dockerfile
  networks:
    - ubsv-network
  volumes:
    - ./data:/app/data
  expose:
    - 8081-8093

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    networks:
      - ubsv-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: really_strong_password_change_me
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - ./scripts/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data:/app/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  # Define node-specific configurations as extensions
  ubsv-1:
    <<: *ubsv-base
    environment:
      SETTINGS_CONTEXT: "docker.ci.ubsv1"
      startCoinbase: false
      asset_httpAddress: "http://ubsv-1:8090"
      utxostore: postgres://miner1:miner1@postgres:5432/ubsv1
      txmeta_store: postgres://miner1:miner1@postgres:5432/ubsv1
      blockchain_store: postgres://miner1:miner1@postgres:5432/ubsv1
      coinbase_store: postgres://coinbase:coinbase@postgres:5432/coinbase
      startTxMetaStore: "false"
      txstore: badger:///data/ubsv1/txstore
      subtreestore: badger:///data/ubsv1/subtreestore
      mine_initial_blocks: true
      mine_initial_blocks_count: 200
      coinbase_wallet_private_key: "L56TgyTpDdvL3W24SMoALYotibToSCySQeo4pThLKxw6EFR6f93Q"
      startBootstrap: false
      startP2P: true
      feature_libP2P: true
      feature_bootstrap: false
      securityLevelGRPC: 0
      securityLevelHTTP: 0
      blockchain_grpcAddress: "ubsv-1:8087"
      blockvalidation_httpAddress: "http://localhost:8088"
      coinbase_should_wait: true
      coinbase_wait_until_block: 210
    ports:
      - "18081-18089:8081-8089"
      - "18090-18093:8090-8093"

  ubsv-2:
    <<: *ubsv-base
    command: ["./ubsv", "-miner=0", "-coinbase=0"]
    environment:
      SETTINGS_CONTEXT: "docker.ci.ubsv2"
      startCoinbase: false
      asset_httpAddress: "http://ubsv-2:8090"
      utxostore: postgres://miner2:miner2@postgres:5432/ubsv2
      txmeta_store: postgres://miner2:miner2@postgres:5432/ubsv2
      blockchain_store: postgres://miner2:miner2@postgres:5432/ubsv2
      coinbase_store: postgres://coinbase:coinbase@postgres:5432/coinbase
      startTxMetaStore: "false"
      txstore: badger:///data/ubsv2/txstore
      subtreestore: badger:///data/ubsv2/subtreestore
      coinbase_wallet_private_key: "KyAwSjuXZNgj78w3W7mR1fVMbPFu2heaCJJkWK5Yy58NZ4xafV6k"
      startBootstrap: false
      feature_bootstrap: false
      startP2P: true
      feature_libP2P: true
      mine_initial_blocks: false
      securityLevelGRPC: 0
      securityLevelHTTP: 0
      blockchain_grpcAddress: "ubsv-2:8087"
      coinbase_should_wait: true
      coinbase_wait_until_block: 210
    ports:
      - "28081-28089:8081-8089"
      - "28090-28093:8090-8093"

  # ubsv-3:
  #   <<: *ubsv-base
  #   environment:
  #     SETTINGS_CONTEXT: "docker.ci"
  #     asset_httpAddress: "http://ubsv-3:8090"
  #     utxostore: postgres://miner3:miner3@postgres:5432/ubsv3
  #     txmeta_store: postgres://miner3:miner3@postgres:5432/ubsv3
  #     blockchain_store: postgres://miner3:miner3@postgres:5432/ubsv3
  #     coinbase_store: postgres://coinbase:coinbase@postgres:5432/coinbase
  #     startTxMetaStore: "false"
  #     txstore: badger:///data/ubsv3/txstore
  #     subtreestore: badger:///data/ubsv3/subtreestore
  #     coinbase_wallet_private_key: L3NVjmwg3nC7ZPrwMVF6FXiG1a1RZ89nhizmJVctGztRKLYrhtFL
  #     bootstrap_grpcAddress: "http://ubsv-1:8089"
  #     bootstrap_grpcListenAddress: "http://localhost:8089"
  #   ports:
  #     - "38081-38089:8081-8089"
  #     - "38090-38093:8090-8093"

# Add more ubsv nodes as needed

networks:
  ubsv-network:
    name: my-ubsv-network
