version: '3.8'

services:
  ubsv-1:
    container_name: ubsv-1
    image: taal/ubsv:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "18081-18088:8081-8088"
      - "18090-18091:8090-8091"

  ubsv-2:
    container_name: ubsv-2
    image: taal/ubsv:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "28081-28088:8081-8088"
      - "28090-28091:8090-8091"

  ubsv-3:
    container_name: ubsv-3
    image: taal/ubsv:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "38081-38088:8081-8088"
      - "38090-38091:8090-8091"
  
networks:
  network1:
    name: my-pre-existing-network
    external: true

