version: '3.8'

# Define a common base configuration for ubsv nodes
x-ubsv-base:
  &ubsv-base
  image: ubsv:latest
  depends_on:
    - postgres
  networks:
    - ubsv-network
  volumes:
    - ./data:/app/data
  expose:
    - 8081-8093

networks:
  ubsv-network:
    name: my-ubsv-network

services:
  ubsv-builder:
    image: ubsv:latest
    build:
      context: .
      dockerfile: local.Dockerfile
      args:
        BASE_IMG: 434394763103.dkr.ecr.eu-north-1.amazonaws.com/ubsv:base-build-2db1b0e
        RUN_IMG: 434394763103.dkr.ecr.eu-north-1.amazonaws.com/ubsv:base-run-2db1b0e
    networks:
    - ubsv-network
    entrypoint: ["pwd"]

  postgres:
    container_name: postgres
    image: postgres:latest
    networks:
      - ubsv-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: really_strong_password_change_me
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - ./scripts/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  aerospike-1:
    container_name: aerospike-1
    image: aerospike/aerospike-server:latest
    networks:
      - ubsv-network
    environment:
      REPL_FACTOR: 0
      MEM_GB: 1
      DEFAULT_TTL: 30d
      STORAGE_GB: 4
    ports:
      - 3100:3000

  aerospike-2:
    container_name: aerospike-2
    image: aerospike/aerospike-server:latest
    networks:
      - ubsv-network
    environment:
      REPL_FACTOR: 0
      MEM_GB: 1
      DEFAULT_TTL: 30d
      STORAGE_GB: 4
    ports:
      - 3200:3000

  aerospike-3:
    container_name: aerospike-3
    image: aerospike/aerospike-server:latest
    networks:
      - ubsv-network
    environment:
      REPL_FACTOR: 0
      MEM_GB: 1
      DEFAULT_TTL: 30d
      STORAGE_GB: 4
    ports:
      - 3300:3000

  ubsv-1:
    <<: *ubsv-base
    depends_on:
            - aerospike-1
            - postgres
    entrypoint: ["/app/wait.sh", "aerospike-1", "3000", "2", "--", "/app/ubsv.run", "-miner=1", "-coinbase=1"]
    environment:
      SETTINGS_CONTEXT: "docker.ci.ubsv1"
      logLevel: "INFO"
      # utxostore: postgres://miner1:miner1@postgres:5432/ubsv1
      # txmeta_store: postgres://miner1:miner1@postgres:5432/ubsv1
      utxostore: aerospike://aerospike-1:3000/test?WarmUp=32&ConnectionQueueSize=32&LimitConnectionsToQueueSize=true&MinConnectionsPerNode=8&expiration=300
      txmeta_store: aerospike://aerospike-1:3000/test?WarmUp=32&ConnectionQueueSize=32&LimitConnectionsToQueueSize=true&MinConnectionsPerNode=8&expiration=300
      blockchain_store: postgres://miner1:miner1@postgres:5432/ubsv1
      coinbase_store: postgres://coinbase1:coinbase1@postgres:5432/coinbase1
      startTxStore: "true"
      txstore: file:///data/ubsv1/txstore
      subtreestore: file:///data/ubsv1/subtreestore
      mine_initial_blocks: true
      miner_wallet_private_keys: "L56TgyTpDdvL3W24SMoALYotibToSCySQeo4pThLKxw6EFR6f93Q | KyAwSjuXZNgj78w3W7mR1fVMbPFu2heaCJJkWK5Yy58NZ4xafV6k | L32b9pdNPxXhqEA5VvzMb8wQ1NPpRXFmViFgEewjkVg8ZgH23b6w"
      startBootstrap: false
      startP2P: true
      feature_libP2P: true
      feature_bootstrap: false
      blockchain_grpcAddress: "ubsv-1:8087"
      blockvalidation_httpAddress: "http://localhost:8088"
      propagation_grpcAddresses: localhost:8084 | ubsv-2:8084 | ubsv-3:8084
    volumes:
      - ./settings_local.conf:/app/settings_local.conf
    #   - ./data/ubsv1/txstore:/data/ubsv1/txstore
    #   - ./data/ubsv1/subtreestore:/data/ubsv1/subtreestore
    ports:
      - "18081-18089:8081-8089"
      - "18090-18092:8090-8092"
      - "19091:9091"

  ubsv-2:
    <<: *ubsv-base
    depends_on:
      - aerospike-2
    entrypoint: ["/app/wait.sh", "aerospike-2", "3000", "2", "--", "/app/ubsv.run", "-miner=1", "-coinbase=1"]
    environment:
      SETTINGS_CONTEXT: "docker.ci.ubsv2"
      logLevel: "INFO"
      # utxostore: postgres://miner2:miner2@postgres:5432/ubsv2
      # txmeta_store: postgres://miner2:miner2@postgres:5432/ubsv2
      utxostore: aerospike://aerospike-2:3000/test?WarmUp=32&ConnectionQueueSize=32&LimitConnectionsToQueueSize=true&MinConnectionsPerNode=8&expiration=300
      txmeta_store: aerospike://aerospike-2:3000/test?WarmUp=32&ConnectionQueueSize=32&LimitConnectionsToQueueSize=true&MinConnectionsPerNode=8&expiration=300
      blockchain_store: postgres://miner2:miner2@postgres:5432/ubsv2
      coinbase_store: postgres://coinbase2:coinbase2@postgres:5432/coinbase2
      startTxStore: "true"
      txstore: file:///data/ubsv2/txstore
      subtreestore: file:///data/ubsv2/subtreestore
      miner_wallet_private_keys: "L56TgyTpDdvL3W24SMoALYotibToSCySQeo4pThLKxw6EFR6f93Q | KyAwSjuXZNgj78w3W7mR1fVMbPFu2heaCJJkWK5Yy58NZ4xafV6k | L32b9pdNPxXhqEA5VvzMb8wQ1NPpRXFmViFgEewjkVg8ZgH23b6w"
      startBootstrap: false
      feature_bootstrap: false
      startP2P: true
      feature_libP2P: true
      mine_initial_blocks: false
      blockchain_grpcAddress: "ubsv-2:8087"
      blockvalidation_httpAddress: "http://localhost:8088"
      propagation_grpcAddresses: ubsv-1:8084 | ubsv-2:8084 | ubsv-3:8084
    volumes:
      - ./settings_local.conf:/app/settings_local.conf
      - ./data/ubsv2/txstore:/data/ubsv2/txstore
      - ./data/ubsv2/subtreestore:/data/ubsv2/subtreestore
    ports:
      - "28081-28089:8081-8089"
      - "28090-28092:8090-8092"
      - "29091:9091"

  ubsv-3:
    <<: *ubsv-base
    depends_on:
      - aerospike-3
    entrypoint: ["/app/wait.sh", "aerospike-3", "3000", "2", "--", "/app/ubsv.run", "-miner=1", "-coinbase=1"]
    environment:
      SETTINGS_CONTEXT: "docker.ci.ubsv3"
      logLevel: "INFO"
      # utxostore: postgres://miner3:miner3@postgres:5432/ubsv3
      # txmeta_store: postgres://miner3:miner3@postgres:5432/ubsv3
      utxostore: aerospike://aerospike-3:3000/test?WarmUp=32&ConnectionQueueSize=32&LimitConnectionsToQueueSize=true&MinConnectionsPerNode=8&expiration=300
      txmeta_store: aerospike://aerospike-3:3000/test?WarmUp=32&ConnectionQueueSize=32&LimitConnectionsToQueueSize=true&MinConnectionsPerNode=8&expiration=300
      blockchain_store: postgres://miner3:miner3@postgres:5432/ubsv3
      coinbase_store: postgres://coinbase3:coinbase3@postgres:5432/coinbase3
      startTxStore: "true"
      txstore: file:///data/ubsv3/txstore
      subtreestore: file:///data/ubsv3/subtreestore
      miner_wallet_private_keys: "L56TgyTpDdvL3W24SMoALYotibToSCySQeo4pThLKxw6EFR6f93Q | KyAwSjuXZNgj78w3W7mR1fVMbPFu2heaCJJkWK5Yy58NZ4xafV6k | L32b9pdNPxXhqEA5VvzMb8wQ1NPpRXFmViFgEewjkVg8ZgH23b6w"
      startBootstrap: false
      feature_bootstrap: false
      startP2P: true
      feature_libP2P: true
      mine_initial_blocks: false
      blockchain_grpcAddress: "ubsv-3:8087"
      blockvalidation_httpAddress: "http://localhost:8088"
      propagation_grpcAddresses: ubsv-1:8084 | ubsv-2:8084 | ubsv-3:8084
    volumes:
      - ./settings_local.conf:/app/settings_local.conf
      - ./data/ubsv3/txstore:/data/ubsv3/txstore
      - ./data/ubsv3/subtreestore:/data/ubsv3/subtreestore
    ports:
      - "38081-38089:8081-8089"
      - "38090-38092:8090-8092"
      - "39091:9091"

  tx-blaster-1:
    <<: *ubsv-base
    depends_on:
      - ubsv-1
      - ubsv-2
      - ubsv-3
    environment:
      SETTINGS_CONTEXT: "docker.ci"
      tx_blaster_profilerAddr: ":9092"
      asset_httpAddress: "http://ubsv-1:8090"
      propagation_grpcAddresses: ubsv-1:8084 | ubsv-2:8084 | ubsv-3:8084
      coinbase_grpcAddress: ubsv-1:8093
      coinbase_store: postgres://coinbase1:coinbase1@postgres:5432/coinbase1
      blockchain_store: postgres://miner1:miner1@postgres:5432/ubsv1
      utxostore: postgres://miner1:miner1@postgres:5432/ubsv1
      coinbase_assetGrpcAddress: ubsv-1:8091
      BLASTER_ARGS: "-workers=2"
      # p2p_bootstrapAddresses: "/ip4/172.24.0.2/tcp/9901/p2p/12D3KooWS43tBXaGewmskvL1B82KccLP5JafTvreiJNbHCbZhDnh"
      p2p_bootstrapAddresses: "/dns4/p2p-bootstrap-1/tcp/9901/p2p/12D3KooWJ6kQHAR65xkA34NABsNVAJyVxPWh8JUSo1vtZsTyw4GD"
      propagation_quicAddresses: https://ubsv-1:8384 | https://ubsv-2:8384 | https://ubsv-3:8384
    # pass arguments to the command
    command: ["/app/blaster.run", "-workers=10", "-print=0", "-profile=:9092", "-log=0", "-limit=200", "--quic=false"]
    networks:
      - ubsv-network
    volumes:
      - ./settings_local.conf:/app/settings_local.conf
      - ./data/txblaster1:/app/data
      # - ./data/txblaster.log:/app/data/txblaster.log

  tx-blaster-2:
    <<: *ubsv-base
    depends_on:
      - ubsv-1
      - ubsv-2
      - ubsv-3
    environment:
      SETTINGS_CONTEXT: "docker.ci"
      tx_blaster_profilerAddr: ":9092"
      asset_httpAddress: "http://ubsv-2:8090"
      propagation_grpcAddresses: ubsv-1:8084 | ubsv-2:8084 | ubsv-3:8084
      coinbase_grpcAddress: ubsv-2:8093
      coinbase_store: postgres://coinbase2:coinbase2@postgres:5432/coinbase2
      blockchain_store: postgres://miner2:miner2@postgres:5432/ubsv2
      utxostore: postgres://miner2:miner2@postgres:5432/ubsv2
      coinbase_assetGrpcAddress: ubsv-2:8091
      BLASTER_ARGS: "-workers=2"
      # p2p_bootstrapAddresses: "/ip4/172.24.0.2/tcp/9901/p2p/12D3KooWS43tBXaGewmskvL1B82KccLP5JafTvreiJNbHCbZhDnh"
      p2p_bootstrapAddresses: "/dns4/p2p-bootstrap-1/tcp/9901/p2p/12D3KooWS43tBXaGewmskvL1B82KccLP5JafTvreiJNbHCbZhDnh"
      propagation_quicAddresses: https://ubsv-1:8384 | https://ubsv-2:8384 | https://ubsv-3:8384
    # pass arguments to the command
    command: ["/app/blaster.run", "-workers=10", "-print=0", "-profile=:9092", "-log=0", "-limit=200", "--quic=false"]
    networks:
      - ubsv-network
    volumes:
      - ./settings_local.conf:/app/settings_local.conf
      - ./data/txblaster2:/app/data
      # - ./data/txblaster.log:/app/data/txblaster.log

  tx-blaster-3:
    <<: *ubsv-base
    depends_on:
      - ubsv-1
      - ubsv-2
      - ubsv-3
    environment:
      SETTINGS_CONTEXT: "docker.ci"
      tx_blaster_profilerAddr: ":9092"
      asset_httpAddress: "http://ubsv-3:8090"
      propagation_grpcAddresses: ubsv-1:8084 | ubsv-2:8084 | ubsv-3:8084
      coinbase_grpcAddress: ubsv-3:8093
      coinbase_store: postgres://coinbase3:coinbase3@postgres:5432/coinbase3
      blockchain_store: postgres://miner3:miner3@postgres:5432/ubsv3
      utxostore: postgres://miner3:miner3@postgres:5432/ubsv3
      coinbase_assetGrpcAddress: ubsv-3:8091
      BLASTER_ARGS: "-workers=2"
      # p2p_bootstrapAddresses: "/ip4/172.24.0.2/tcp/9901/p2p/12D3KooWS43tBXaGewmskvL1B82KccLP5JafTvreiJNbHCbZhDnh"
      p2p_bootstrapAddresses: "/dns4/p2p-bootstrap-1/tcp/9901/p2p/12D3KooWS43tBXaGewmskvL1B82KccLP5JafTvreiJNbHCbZhDnh"
      propagation_quicAddresses: https://ubsv-1:8384 | https://ubsv-2:8384 | https://ubsv-3:8384
    # pass arguments to the command
    command: ["/app/blaster.run", "-workers=10", "-print=0", "-profile=:9092", "-log=0", "-limit=200", "--quic=false"]
    networks:
      - ubsv-network
    volumes:
      - ./settings_local.conf:/app/settings_local.conf
      - ./data/txblaster2:/app/data
      # - ./data/txblaster.log:/app/data/txblaster.log

  prometheus:
    image: prom/prometheus:v2.44.0
    ports:
      - "9090:9090"
    networks:
      - ubsv-network
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

# Add more ubsv nodes as needed
