{
 "title": "Teranode - Block Persister",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "grouping_interval",
    "label": "Grouping Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(propagation_transactions_size_sum,instance)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(propagation_transactions_size_count,namespace)"
    }
   },
   { "name": "srvc", "label": "Service", "query": { "query": "label_values(service)" } },
   { "name": "prometheus", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Validator Processed Transactions",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(increase(validator_transactions_validate_total_count{instance=~\"$instance\",service=~\"$srvc\",namespace=~\"$namespace\"}[$grouping_interval])) by (service) / 60  >0",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Percentiles -> BA",
   "type": "stat",
   "description": "Average across all nodes counted into buckets from 0 to 2^16",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg by (namespace) (histogram_quantile(0.95, (sum(rate(validator_transactions_validate_total_bucket{instance=~\"$instance\",service=~\"$srvc\",namespace=~\"$namespace\"}[$grouping_interval])))))",
     "legendFormat": "p95 us"
    },
    {
     "expr": "avg by (namespace) (histogram_quantile(0.99, (sum(rate(validator_transactions_validate_total_micros_bucket{instance=~\"$instance\",service=~\"$srvc\",namespace=~\"$namespace\"}[$grouping_interval])))))",
     "legendFormat": "p99 us"
    },
    {
     "expr": "avg by (namespace) (histogram_quantile(0.999, (sum(rate(validator_transactions_validate_total_micros_bucket{instance=~\"$instance\",service=~\"$srvc\",namespace=~\"$namespace\"}[$grouping_interval])))))",
     "legendFormat": "p99.9 us"
    }
   ]
  },
  {
   "title": "Subtree Batch Duration",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 10 },
   "targets": [
    {
     "expr": "sum(increase(blockpersister_subtree_batch_millis{instance=~\"$instance\",service=~\"$srvc\",namespace=~\"$namespace\"}[$grouping_interval])) by (le)",
     "legendFormat": "{{ le }}us"
    }
   ]
  },
  {
   "title": "Subtree Duration",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 19 },
   "targets": [
    {
     "expr": "sum(increase(blockpersister_subtrees_duration_millis{instance=~\"$instance\",service=~\"$srvc\",namespace=~\"$namespace\"}[$grouping_interval])) by (le)",
     "legendFormat": "{{ le }}us"
    }
   ]
  },
  {
   "title": "Block Duration",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 28 },
   "targets": [
    {
     "expr": "sum(increase(blockvalidation_block_found_bucket{instance=~\"$instance\",service=~\"$srvc\",namespace=~\"$namespace\"}[$grouping_interval])) by (le)",
     "legendFormat": "{{ le }}us"
    }
   ]
  }
 ]
}