{
 "title": "Teranode - Legacy Service",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1h",
 "templating": {
  "list": [
   {
    "name": "grouping_interval",
    "label": "Grouping Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(propagation_transactions_size_sum,instance)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(propagation_transactions_size_count,namespace)"
    }
   },
   { "name": "srvc", "label": "Service", "query": { "query": "label_values(service)" } },
   { "name": "prometheus", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Blocks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Block height",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "legacy_netsync_block_height{instance=~\"$instance\",service=~\"$srvc\",namespace=~\"$namespace\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Block Processing",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(increase(legacy_netsync_handle_block_direct_bucket{instance=~\"$instance\",service=~\"$srvc\",namespace=~\"$namespace\"}[$grouping_interval])) by (le)",
     "legendFormat": "{{ le }}us"
    }
   ]
  },
  { "title": "Prepare Subtree", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Prepare Subtree",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(increase(legacy_netsync_prepare_subtrees_bucket{instance=~\"$instance\",service=~\"$srvc\",namespace=~\"$namespace\"}[$grouping_interval])) by (le)",
     "legendFormat": "{{ le }}us"
    }
   ]
  },
  {
   "title": "Extend TXs",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum(increase(legacy_netsync_extend_transactions_bucket{instance=~\"$instance\",service=~\"$srvc\",namespace=~\"$namespace\"}[$grouping_interval])) by (le)",
     "legendFormat": "{{ le }}us"
    }
   ]
  },
  {
   "title": "Validate TXs",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "sum(increase(legacy_netsync_validate_transactions_legacy_mode_bucket{instance=~\"$instance\",service=~\"$srvc\",namespace=~\"$namespace\"}[$grouping_interval])) by (le)",
     "legendFormat": "{{ le }}us"
    }
   ]
  },
  {
   "title": "Nr Inputs",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "sum(increase(legacy_netsync_block_tx_nr_inputs_bucket{instance=~\"$instance\",service=~\"$srvc\",namespace=~\"$namespace\"}[$grouping_interval])) by (le)",
     "legendFormat": "{{ le }}us"
    }
   ]
  },
  {
   "title": "Nr Outputs",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "sum(increase(legacy_netsync_block_tx_nr_outputs_bucket{instance=~\"$instance\",service=~\"$srvc\",namespace=~\"$namespace\"}[$grouping_interval])) by (le)",
     "legendFormat": "{{ le }}us"
    }
   ]
  },
  {
   "title": "TX Size",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "sum(increase(legacy_netsync_block_tx_size_bucket{instance=~\"$instance\",service=~\"$srvc\",namespace=~\"$namespace\"}[$grouping_interval])) by (le)",
     "legendFormat": "{{ le }}us"
    }
   ]
  },
  {
   "title": "External TXs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 },
   "collapsed": true,
   "panels": [
    {
     "title": "External TXs - Set",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 47 },
     "targets": [
      {
       "expr": "sum(increase(aerospike_set_external_bucket{instance=~\"$instance\",service=~\"$srvc\",namespace=~\"$namespace\"}[$grouping_interval])) by (le)",
       "legendFormat": "{{ le }}us"
      }
     ]
    },
    {
     "title": "External TXs - Get",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 55 },
     "targets": [
      {
       "expr": "sum(increase(aerospike_get_external_bucket{instance=~\"$instance\",service=~\"$srvc\",namespace=~\"$namespace\"}[$grouping_interval])) by (le)",
       "legendFormat": "{{ le }}us"
      }
     ]
    }
   ]
  }
 ]
}