{
 "title": "Teranode - Service Overview",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "grouping_interval",
    "label": "Grouping Interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(propagation_transactions_size_sum,instance)"
    }
   },
   { "name": "namespace", "label": "Namespace", "query": { "query": "label_values(namespace)" } },
   { "name": "srvc", "label": "Service", "query": { "query": "label_values(service)" } },
   { "name": "prometheus", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Processed Transaction by Service",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "(sum(increase(propagation_transactions_count{instance=~\"$instance\",service=~\"$srvc\",namespace=~\"$namespace\"}[$grouping_interval])) by (service,) >0) / 60",
     "legendFormat": "Propagation - {{service}}"
    },
    {
     "expr": "sum(increase(tx_blaster_processed_transactions{instance=~\"$instance\",service=~\"$srvc\",namespace=~\"$namespace\"}[$grouping_interval])) / 60",
     "legendFormat": "Tx Blaster "
    },
    {
     "expr": "sum(increase(blockassembly_transactions{instance=~\"$instance\",service=~\"$srvc\",namespace=~\"$namespace\"}[$grouping_interval]))  by (service,) / 60",
     "legendFormat": "Blockassembly - {{service}}"
    }
   ]
  },
  {
   "title": "TX Blaster Generated Transaction",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(tx_blaster_workers{service=~\"tx-blaster-service.*\",namespace=~\"$namespace\"})",
     "legendFormat": "workers"
    },
    {
     "expr": "sum(increase(tx_blaster_processed_transactions{service=~\"$srvc\",namespace=~\"$namespace\"}[$grouping_interval])) by (instance,) / 60 > 0",
     "legendFormat": "Valid-{{instance}}"
    },
    {
     "expr": "sum(increase(tx_blaster_invalid_transactions{service=~\"$srvc\",namespace=~\"$namespace\"}[$grouping_interval])) by (instance) / 60 > 0",
     "legendFormat": "Invalid-{{instance}}"
    },
    {
     "expr": "sum(increase(tx_blaster_retry_transactions{service=~\"$srvc\",namespace=~\"$namespace\"}[$grouping_interval])) by (instance) / 60 > 0",
     "legendFormat": "Retries-{{instance}}"
    }
   ]
  },
  {
   "title": "Propagation Processed Transaction per Instance",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "(sum(increase(propagation_transactions_count{instance=~\"$instance\",service=~\"$srvc\",namespace=~\"$namespace\"}[$grouping_interval])) by (instance,) >0) / 60",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "(sum(increase(propagation_invalid_transactions_count{instance=~\"$instance\",service=~\"$srvc\",namespace=~\"$namespace\"}[$grouping_interval])) by (instance,) >0) / 60",
     "legendFormat": "Invalid: {{instance}}"
    }
   ]
  },
  {
   "title": "Propagation Processed Transaction per node",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "(sum(increase(propagation_transactions_count{instance=~\"$instance\",service=~\"$srvc\",namespace=~\"$namespace\"}[$grouping_interval])) by (node,) >0) / 60",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(go_goroutines) by (namespace,service)",
     "legendFormat": "{{namespace}}: {{service}}"
    }
   ]
  },
  {
   "title": "Transactions Added by Block Assembly /second",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(increase(blockassembly_transactions{service=~\"$srvc\",namespace=~\"$namespace\"}[$grouping_interval])) by (service) / 60",
     "legendFormat": "Transactions-{{service}}"
    }
   ]
  },
  {
   "title": "Transactions In Block Assembly",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "(sum(blockassembly_transactions{instance=~\"$instance\",service=~\"$srvc\",service!~\"tx-blaster.*\",namespace=~\"$namespace\"}) by (service,) >0)",
     "legendFormat": "Transactions"
    },
    {
     "expr": "(sum(blockassembly_queued_transactions{instance=~\"$instance\",service=~\"$srvc\",service!~\"tx-blaster.*\",namespace=~\"$namespace\"}) by (service,) >0)",
     "legendFormat": "Queued"
    },
    {
     "expr": "\n(sum(blockassembly_subtrees{instance=~\"$instance\",service=~\"$srvc\",service!~\"tx-blaster.*\",namespace=~\"$namespace\"}) by (service,) >0) / 60",
     "legendFormat": "Subtrees"
    }
   ]
  },
  {
   "title": "Transactions Added to Kafka /second",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(increase(validator_validator_send_to_block_assembly_count{service=~\"$srvc\",namespace=~\"$namespace\"}[$grouping_interval])) by (service) / 60 > 0",
     "legendFormat": "Tx Data (block assembly)"
    },
    {
     "expr": "sum(increase(validator_send_to_blockvalidation_kafka_micros_count{service=~\"$srvc\",namespace=~\"$namespace\"}[$grouping_interval])) by (service) / 60 > 0",
     "legendFormat": "Tx Meta (block/subtree validation)"
    }
   ]
  },
  {
   "title": "Tx Meta read from Kafka /second",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(increase(subtreevalidation_set_tx_meta_cache_kafka_count{service=~\"$srvc\",namespace=~\"$namespace\"}[$grouping_interval])) by (service,instance) / 60 > 0",
     "legendFormat": "{{service}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Tx Blaster workers",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(tx_blaster_workers{namespace=~\"$namespace\"})by (instance,)   >0",
     "legendFormat": "Workers-{{instance}}"
    },
    {
     "expr": "sum(tx_blaster_worker_errors{namespace=~\"$namespace\"}) by (instance,)  >0",
     "legendFormat": "Worker errors - {{instance}}"
    }
   ]
  },
  {
   "title": "Queued Blocks in Block Validation",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(blockvalidation_block_found_ch{service!~\"tx-blaster.*\",service=~\"$srvc\",namespace=~\"$namespace\"}) by (service)",
     "legendFormat": "Blocks queued-{{service}}"
    },
    {
     "expr": "sum(blockvalidation_catchup_count{service!~\"tx-blaster.*\",service=~\"$srvc\",namespace=~\"$namespace\"}) by (service)",
     "legendFormat": "Blocks catchup-{{service}}"
    }
   ]
  },
  {
   "title": "Subtrees processed by Subtree Validation",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(increase(subtreevalidation_validate_subtree_count{service!~\"tx-blaster.*\",service=~\"$srvc\",namespace=~\"$namespace\"}[$grouping_interval])) by (service) / 60",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Size of Catchup Channel in Block Validation",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(blockvalidation_catchup_ch{service!~\"tx-blaster.*\",service=~\"$srvc\",namespace=~\"$namespace\"}) by (service)",
     "legendFormat": "Blocks catchup-{{service}}"
    }
   ]
  },
  {
   "title": "Subtrees processed",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 91 },
   "targets": [
    {
     "expr": "sum(subtreevalidation_validate_subtree_count{service=~\"$srvc\",namespace=~\"$namespace\"}) by (service) >0",
     "legendFormat": "Count: {{service}}"
    },
    {
     "expr": "sum(subtreevalidation_validate_subtree_duration_sum{service=~\"$srvc\",namespace=~\"$namespace\"}) by (service) >0",
     "legendFormat": "Duration: {{service}}"
    }
   ]
  },
  {
   "title": "Block Chain Mined Block",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 91 },
   "targets": [
    {
     "expr": "sum(increase(blockchain_add_block_count{service=~\"$srvc\",namespace=~\"$namespace\"}[1m])) by (service) >0",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Aerospike UTXO",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(increase(aerospike_utxo_create_batch_count[$grouping_interval])) / 60",
     "legendFormat": "UTXO: Batch Create"
    },
    {
     "expr": "sum(increase(aerospike_utxo_store[$grouping_interval])) / 60",
     "legendFormat": "UTXO: Store"
    },
    {
     "expr": "sum(increase(aerospike_utxo_spend_batch_count[$grouping_interval])) / 60",
     "legendFormat": "UTXO: Spend Batch"
    },
    {
     "expr": "sum(increase(aerospike_map_utxo_reset[$grouping_interval])) / 60",
     "legendFormat": "Map: Restore"
    },
    {
     "expr": "sum(increase(aerospike_map_utxo_spend[$grouping_interval])) / 60",
     "legendFormat": "Map: Spend"
    },
    {
     "expr": "sum(increase(aerospike_map_utxo_respend[$grouping_interval])) / 60",
     "legendFormat": "Map: Respend"
    },
    {
     "expr": "sum(increase(aerospike_map_utxo_reset[$grouping_interval])) / 60",
     "legendFormat": "Map: Reset"
    }
   ]
  },
  {
   "title": "Aerospike Tx Meta",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(increase(aerospike_map_txmeta_get[$grouping_interval])) / 60",
     "legendFormat": "Get"
    },
    {
     "expr": "sum(increase(aerospike_map_txmeta_set_mined[$grouping_interval]))/ 60",
     "legendFormat": "Set"
    },
    {
     "expr": "sum(increase(aerospike_map_txmeta_delete[$grouping_interval]))/ 60",
     "legendFormat": "Delete"
    },
    {
     "expr": "sum(increase(aerospike_map_txmeta_set_mined[$grouping_interval]))/ 60",
     "legendFormat": "Set-Mined"
    },
    {
     "expr": "sum(increase(aerospike_map_txmeta_set_mined_batch[$grouping_interval]))/ 60",
     "legendFormat": "Set-Mined-Batch"
    },
    {
     "expr": "sum(increase(aerospike_map_txmeta_set_mined_batch_n[$grouping_interval]))/ 60",
     "legendFormat": "Set-Mined-BatchN"
    },
    {
     "expr": "sum(increase(aerospike_txmeta_get_multi_n[$grouping_interval]))/ 60",
     "legendFormat": "Get-Multi-BatchN"
    },
    {
     "expr": "sum(increase(aerospike_txmeta_set_mined_batch_err_n[$grouping_interval]))/ 60",
     "legendFormat": "Set-Multi-ErrN"
    },
    {
     "expr": "sum(increase(aerospike_map_txmeta_set_mined_batch[$grouping_interval]))/ 60",
     "legendFormat": "Set-Batch"
    },
    {
     "expr": "sum(increase(aerospike_map_txmeta_get_multi[$grouping_interval])) / 60",
     "legendFormat": "Get-Multi"
    }
   ]
  },
  {
   "title": "Aerospike MAP UTXO",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(increase(aerospike_map_utxo_get[$grouping_interval])) / 60",
     "legendFormat": "Get"
    },
    {
     "expr": "sum(increase(aerospike_map_utxo_store[$grouping_interval])) / 60",
     "legendFormat": "Store"
    },
    {
     "expr": "sum(increase(aerospike_map_utxo_store_spent[$grouping_interval])) / 60",
     "legendFormat": "Spent"
    },
    {
     "expr": "sum(increase(aerospike_map_utxo_restore[$grouping_interval])) / 60",
     "legendFormat": "Restore"
    },
    {
     "expr": "sum(increase(aerospike_map_utxo_spend[$grouping_interval])) / 60",
     "legendFormat": "Spend"
    },
    {
     "expr": "sum(increase(aerospike_map_utxo_respend[$grouping_interval])) / 60",
     "legendFormat": "Respend"
    },
    {
     "expr": "sum(increase(aerospike_map_utxo_spend_spent[$grouping_interval])) / 60",
     "legendFormat": "Spend Spent"
    },
    {
     "expr": "sum(increase(aerospike_map_utxo_reset[$grouping_interval])) / 60",
     "legendFormat": "Reset"
    }
   ]
  },
  {
   "title": "Aerospike MAP Tx Meta",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(increase(aerospike_map_txmeta_get[$grouping_interval])) / 60",
     "legendFormat": "Get"
    },
    {
     "expr": "sum(increase(aerospike_map_txmeta_store[$grouping_interval]))/ 60",
     "legendFormat": "Set"
    },
    {
     "expr": "sum(increase(aerospike_map_txmeta_delete[$grouping_interval]))/ 60",
     "legendFormat": "Delete"
    },
    {
     "expr": "sum(increase(aerospike_map_txmeta_set_mined[$grouping_interval]))/ 60",
     "legendFormat": "Set-Mined"
    },
    {
     "expr": "sum(increase(aerospike_map_txmeta_set_mined_batch[$grouping_interval]))/ 60",
     "legendFormat": "Set-Mined-Batch"
    },
    {
     "expr": "sum(increase(aerospike_map_txmeta_set_mined_batch_n[$grouping_interval]))/ 60",
     "legendFormat": "Set-Mined-BatchN"
    },
    {
     "expr": "sum(increase(aerospike_map_txmeta_get_multi_n[$grouping_interval]))/ 60",
     "legendFormat": "Get-Multi-BatchN"
    },
    {
     "expr": "sum(increase(aerospike_map_txmeta_set_mined_batch_err_n[$grouping_interval]))/ 60",
     "legendFormat": "Set-Multi-ErrN"
    },
    {
     "expr": "sum(increase(aerospike_map_utxo_respend[$grouping_interval]))/ 60",
     "legendFormat": "Respends"
    }
   ]
  },
  {
   "title": "Tx Meta Cache in Block Validation",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 130 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(rate(blockvalidation_tx_meta_cache_insertions{service!~\"tx-blaster.*\",service=~\"$srvc\",namespace=~\"$namespace\"}[$grouping_interval])) by (service,instance) > 0 / 60",
     "legendFormat": "Cache insertions - {{service}} - {{instance}}"
    },
    {
     "expr": "sum(rate(blockvalidation_tx_meta_cache_hits{service!~\"tx-blaster.*\",service=~\"$srvc\",namespace=~\"$namespace\"}[$grouping_interval])) by (service,instance) > 0 / 60",
     "legendFormat": "Cache hits - {{service}} - {{instance}}"
    },
    {
     "expr": "sum(rate(blockvalidation_tx_meta_cache_misses{service!~\"tx-blaster.*\",service=~\"$srvc\"}[$grouping_interval])) by (service,instance) > 0 / 60",
     "legendFormat": "Cache misses - {{service}} - {{instance}}"
    },
    {
     "expr": "sum(rate(blockvalidation_tx_meta_cache_evictions{service!~\"tx-blaster.*\",service=~\"$srvc\"}[$grouping_interval])) by (service,instance) > 0 / 60",
     "legendFormat": "Cache evictions - {{service}} - {{instance}}"
    },
    {
     "expr": "sum(rate(blockvalidation_tx_meta_cache_get_origin{service!~\"tx-blaster.*\",service=~\"$srvc\"}[$grouping_interval])) by (service,instance) > 0 / 60",
     "legendFormat": "Get from Aeropsike - {{service}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Tx Meta Cache Size in Block Validation",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 130 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(blockvalidation_tx_meta_cache_size{service!~\"tx-blaster.*\",service=~\"$srvc\",service!~\"tx-blaster.*\",namespace=~\"$namespace\"}) by (service,instance)",
     "legendFormat": "Cache size - {{service}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Queued Subtrees in Block Validation",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 144 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(blockvalidation_subtree_exists_cache{service!~\"tx-blaster.*\",service=~\"$srvc\",service!~\"tx-blaster.*\",namespace=~\"$namespace\"}) by (service)",
     "legendFormat": "Subtrees queued - {{service}}"
    }
   ]
  },
  {
   "title": "Tx Meta Cache Number of Elements Added In Block Validation",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 144 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(blockvalidation_tx_meta_cache_cache_total_elements_added{service!~\"tx-blaster.*\",service=~\"$srvc\",service!~\"tx-blaster.*\",namespace=~\"$namespace\"}) by (service,instance)",
     "legendFormat": "Cache size - {{service}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Asset Service - HTTP Get Subtrees",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 158 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(rate(Asset_http_get_subtree{namespace=~\"$namespace\"}[$grouping_interval])) by (app,)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Queued Blocks in Block Validation",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 158 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(blockvalidation_block_found_ch{service!~\"tx-blaster.*\",service=~\"$srvc\",service!~\"tx-blaster.*\",namespace=~\"$namespace\"}) by (service)",
     "legendFormat": "Blocks queued - {{service}}"
    },
    {
     "expr": "sum(blockvalidation_last_validated_blocks_cache{service!~\"tx-blaster.*\",service=~\"$srvc\",service!~\"tx-blaster.*\",namespace=~\"$namespace\"}) by (service)",
     "legendFormat": "Blocks in RAM - {{service}}"
    }
   ]
  },
  {
   "title": "TX Blaster Errors",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 172 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(increase(tx_blaster_errors{service=~\"$service\",namespace=~\"$namespace\"}[$grouping_interval])) /60",
     "legendFormat": "Get"
    }
   ]
  }
 ]
}