apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 100Gi
  nfs:
    server: nfs-server
    path: /minikube-storage
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
