apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging-teranet-3

configMapGenerator:
  - literals:
      - SETTINGS_CONTEXT=operator.testing.staging-teranet-3
      - asset_centrifuge_disable=true
      - blockassembly_disabled=true
    name: shared-config
    behavior: merge

namePrefix: teranet-3-

patches:
  - path: node-selector-patch.yaml
    target:
      kind: Cluster
  - path: host-patch.yaml
    target:
      kind: Cluster
  - path: resources-patch.yaml
    target:
      kind: Cluster
  - path: enabled-services-patch.yaml
    target:
      kind: Cluster
  - target:
      kind: Cluster
    patch: |-
      - op: replace
        path: /spec/configMapName
        value: teranet-3-shared-config


resources:
  - ../../base
