apiVersion: apps/v1
kind: Deployment
metadata:
  name: seeder
  namespace: seeder-service
  labels:
    monitor: prometheus
    app: seeder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seeder
  template:
    metadata:
      labels:
        app: seeder
        monitor: prometheus
    spec:
      containers:
        - name: seeder
          image: eu.gcr.io/PROJECT/IMAGE:TAG
          args: ["-seeder=1"]
          env:
          - name: SETTINGS_CONTEXT
            value: "kubernetes"
          - name: seeder_grpcAddress
            value: 0.0.0.0:8083
          - name: utxostore
            value: memory://utxostore-service.utxostore-service.svc.cluster.local:8082
          - name: profilerAddr
            value: 0.0.0.0:9091
          - name: JAEGER_AGENT_HOST
            value: jaeger-cluster-agent.jaeger.svc.cluster.local
          - name: JAEGER_AGENT_PORT
            value: "6831"
          - name: SERVICE_NAME
            value: seeder-service
          ports:
            - containerPort: 8083
              protocol: TCP
            - containerPort: 9091
              protocol: TCP
            - containerPort: 4040
              protocol: TCP
          resources:
            requests:
              memory: 1Gi
              cpu: "0.2"
            limits:
              memory: 2Gi
              cpu: "2"
---
apiVersion: v1
kind: Service
metadata:
  name: seeder-service
  namespace: seeder-service
  labels:
    app: seeder
    monitor: prometheus
spec:
  clusterIP: None
  ipFamilyPolicy: SingleStack
  ipFamilies:
  - IPv4
  selector:
    app: seeder
  ports:
    - name: tcp
      port: 8083
      targetPort: 8083
      protocol: TCP
    - name: profiler
      port: 9091
      targetPort: 9091
      protocol: TCP
