apiVersion: apps/v1
kind: Deployment
metadata:
  name: tx-blaster
  namespace: tx-blaster-service
  labels:
    monitor: prometheus
    app: tx-blaster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tx-blaster
  template:
    metadata:
      labels:
        app: tx-blaster
    spec:
      containers:
        - name: tx-blaster
          image: eu.gcr.io/PROJECT/IMAGE:TAG
          args: ["-validator=1", "-tracer=1"]
          env:
          - name: BITCOIN_RPC_URI="bitcoin://bitcoin:bitcoin@localhost:18332" go run .
            value: bitcoin://bitcoin:bitcoin@regtest.regtest.svc.cluster.local:18332
          ports:
            - containerPort: 8081
              protocol: TCP
            - containerPort: 9091
              protocol: TCP
          resources:
            requests:
              memory: 1Gi
              cpu: "0.2"
            limits:
              memory: 2Gi
              cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: tx-blaster-service
  namespace: tx-blaster-service
  labels:
    app: tx-blaster
    monitor: prometheus
spec:
  ipFamilyPolicy: SingleStack
  ipFamilies:
  - IPv4
  selector:
    app: tx-blaster
  ports:
    - name: tcp
      port: 8081
      targetPort: 8081
      protocol: TCP
    - name: profiler
      port: 9091
      targetPort: 9091
      protocol: TCP
