{
 "title": "Latency View",
 "description": "Latency View dashboard helps visualise latencies as number of queries in each bucket as heatmap in various operations like read, write, batch-index, ",
 "tags": [
  "monitoring",
  "latency"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_AEROSPIKE_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job_name",
    "label": "job_name",
    "query": {
     "query": "label_values(aerospike_node_stats_uptime,job)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(aerospike_node_stats_uptime{job=\"$job_name\"},cluster_name)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(aerospike_node_stats_uptime{job=\"$job_name\", cluster_name=~\"$cluster|$^\"},service)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(aerospike_namespace_objects{job=\"$job_name\", cluster_name=~\"$cluster|$^\", service=~\"$node|$^\" },ns)"
    }
   },
   { "name": "operation", "label": "Operation", "query": { "query": "metrics(aerospike_latencies_)" } },
   { "name": "latencytimeunit", "label": "Latency Time Unit", "query": { "query": "metrics(aerospike_latencies_)" } }
  ]
 },
 "panels": [
  {
   "title": "$operation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "operation",
   "targets": [
    {}
   ]
  },
  {
   "title": "Percentiles $operation",
   "type": "stat",
   "description": "Average across all nodes counted into buckets from 0 to 2^16",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg by (ns) (histogram_quantile(0.95, (aerospike_latencies_${operation}_${latencytimeunit}_bucket{job=\"$job_name\",cluster_name=~\"$cluster\", ns=~\"$namespace|$^\"})))",
     "legendFormat": "p95 ${latencytimeunit}"
    },
    {
     "expr": "avg by (ns) (histogram_quantile(0.99, (aerospike_latencies_${operation}_${latencytimeunit}_bucket{job=\"$job_name\",cluster_name=~\"$cluster\", ns=~\"$namespace|$^\"})))",
     "legendFormat": "p99 ${latencytimeunit}"
    },
    {
     "expr": "avg by (ns) (histogram_quantile(0.999, (aerospike_latencies_${operation}_${latencytimeunit}_bucket{job=\"$job_name\",cluster_name=~\"$cluster\", ns=~\"$namespace|$^\"})))",
     "legendFormat": "p99.9 ${latencytimeunit}"
    }
   ]
  },
  {
   "title": "Latency $operation",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "sum by (le) (aerospike_latencies_${operation}_${latencytimeunit}_bucket{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\"})",
     "legendFormat": "{{ le }}${latencytimeunit}"
    }
   ]
  },
  {
   "title": "Max ${operation} latency",
   "type": "timeseries",
   "description": "In ms",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max(aerospike_latencies_${operation}_ms_bucket{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\"})",
     "legendFormat": "Max time"
    }
   ]
  }
 ]
}