{
 "title": "Namespace View",
 "description": "Namespace Overveiw dashboard helps visualise multiple namespaces in multiple clusters and their metrics with a focus on resources in the namespaces.",
 "tags": [
  "monitoring",
  "namespace"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_AEROSPIKE_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job_name",
    "label": "job_name",
    "query": {
     "query": "label_values(aerospike_node_stats_uptime,job)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(aerospike_node_stats_uptime{job=\"$job_name\"},cluster_name)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(aerospike_node_stats_uptime{job=\"$job_name\", cluster_name=~\"$cluster|$^\"},service)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(aerospike_namespace_objects{job=\"$job_name\", cluster_name=~\"$cluster|$^\", service=~\"$node|$^\" },ns)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Namespace: $namespace",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "namespace",
   "targets": [
    {}
   ]
  },
  {
   "title": "Migrations Remaining",
   "type": "stat",
   "description": "Migrations remaining - migrate_rx_partitions_remaining (transmit) migrate_tx_partitions_remaining (receive)",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aerospike_namespace_migrate_tx_partitions_remaining{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
     "legendFormat": "TX"
    },
    {
     "expr": "sum(aerospike_namespace_migrate_rx_partitions_remaining{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
     "legendFormat": "RX"
    }
   ]
  },
  {
   "title": "% Memory Used",
   "type": "bargauge",
   "description": "Namespace memory usage in percentage",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(100-aerospike_namespace_memory_free_pct{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})"
    }
   ]
  },
  {
   "title": "% Memory Trend",
   "type": "timeseries",
   "description": "Namespace memory trend (Used % vs HWM %)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(100-aerospike_namespace_memory_free_pct{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
     "legendFormat": "Memory Used %"
    },
    {
     "expr": "avg(aerospike_namespace_high_water_memory_pct{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
     "legendFormat": "Memory High Water Mark %"
    }
   ]
  },
  {
   "title": "Namespace Memory Statistics",
   "type": "stat",
   "description": "Namespace free memory ((memory_free_pct / 100) * memory_size) in bytes\n\nNamespace total memory (memory_size) in bytes",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(aerospike_namespace_memory_size{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})*(avg(aerospike_namespace_memory_free_pct{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})/100)",
     "legendFormat": "Memory Free"
    },
    {
     "expr": "avg(aerospike_namespace_memory_size{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
     "legendFormat": "Memory Total"
    }
   ]
  },
  {
   "title": "Objects",
   "type": "stat",
   "description": "Namespace objects (tombstones, master_objects, prole_objects, evicted_objects)",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aerospike_namespace_tombstones{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
     "legendFormat": "Tombstones"
    },
    {
     "expr": "sum(aerospike_namespace_evicted_objects{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
     "legendFormat": "Evicted objects"
    },
    {
     "expr": "sum(aerospike_namespace_prole_objects{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
     "legendFormat": "Replica objects"
    },
    {
     "expr": "sum(aerospike_namespace_master_objects{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
     "legendFormat": "Master objects"
    },
    {
     "expr": "sum(aerospike_namespace_expired_objects{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
     "legendFormat": "Expired objects"
    },
    {
     "expr": "sum(aerospike_namespace_unreplicated_records{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
     "legendFormat": "Unreplicated records"
    }
   ]
  },
  {
   "title": "% Storage Used",
   "type": "bargauge",
   "description": "Namespace storage usage in percentage",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(100-aerospike_namespace_device_available_pct{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
     "legendFormat": "Device Used"
    },
    {
     "expr": "avg(100-aerospike_namespace_pmem_available_pct{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
     "legendFormat": "PMEM Used"
    }
   ]
  },
  {
   "title": "% Device Trend",
   "type": "timeseries",
   "description": "Namespace device usage trend",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(100-aerospike_namespace_device_free_pct{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
     "legendFormat": "Used % (100 - device_free_pct)"
    },
    {
     "expr": "avg(100-aerospike_namespace_device_available_pct{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
     "legendFormat": "Used % (100 - device_available_pct)"
    },
    {
     "expr": "avg(aerospike_namespace_high_water_disk_pct{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
     "legendFormat": "Device High Water Mark %"
    }
   ]
  },
  {
   "title": "Namespace Storage Statistics",
   "type": "stat",
   "description": "Namespace free disk space ((device_free_pct / 100) * device_total_bytes)\n\nNamespace device total size in bytes\n\nNamespace device available space in bytes ((device_available_pct/100) * device_total_bytes)\n\nNamespace free pmem space ((pmem_free_pct / 100) * pmem_total_bytes)\n\nNamespace pmem total size in bytes\n\nNamespace pmem available space in bytes ((pmem_available_pct/100) * pmem_total_bytes)",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(aerospike_namespace_device_total_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})*(avg(aerospike_namespace_device_free_pct{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})/100)",
     "legendFormat": "Device Free"
    },
    {
     "expr": "avg(aerospike_namespace_device_total_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
     "legendFormat": "Device Total"
    },
    {
     "expr": "avg(aerospike_namespace_device_total_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})*(avg(aerospike_namespace_device_available_pct{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})/100)",
     "legendFormat": "Device Available"
    },
    {
     "expr": "avg(aerospike_namespace_pmem_total_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})*(avg(aerospike_namespace_pmem_free_pct{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})/100)",
     "legendFormat": "PMEM Free"
    },
    {
     "expr": "avg(aerospike_namespace_pmem_total_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
     "legendFormat": "PMEM Total"
    },
    {
     "expr": "avg(aerospike_namespace_pmem_total_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})*(avg(aerospike_namespace_pmem_available_pct{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})/100)",
     "legendFormat": "PMEM Available"
    }
   ]
  },
  {
   "title": "Partitions",
   "type": "stat",
   "description": "Namespace dead or unavailable partitions",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aerospike_namespace_dead_partitions{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
     "legendFormat": "Dead Partitions"
    },
    {
     "expr": "sum(aerospike_namespace_unavailable_partitions{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
     "legendFormat": "Unavailable Partitions"
    }
   ]
  },
  {
   "title": "Sindexes",
   "type": "stat",
   "description": "Number of Secondary Indexes in this namespace per node",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(sum(aerospike_sets_sindexes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}) by (cluster_name, ns, service))",
     "legendFormat": "Sindexes"
    }
   ]
  },
  {
   "title": "Set Index Populating",
   "type": "stat",
   "description": "Indicates for any set in this namespace whether set index is populating",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(aerospike_sets_index_populating{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}) by (cluster_name,ns)",
     "legendFormat": "Set Index Populating"
    }
   ]
  },
  {
   "title": "Stop Writes / HWM Breached",
   "type": "stat",
   "description": "Namespace stop_writes flag",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aerospike_namespace_stop_writes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
     "legendFormat": "Stop Writes"
    },
    {
     "expr": "sum(aerospike_namespace_clock_skew_stop_writes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
     "legendFormat": "Clock Skew Stop Writes"
    },
    {
     "expr": "sum(aerospike_namespace_hwm_breached{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
     "legendFormat": "HWM Breached"
    }
   ]
  },
  {
   "title": "% Primary Index Device Used (Flash/PMEM)",
   "type": "bargauge",
   "description": "Percentage of device space used by primary index (for flash and PMEM)",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(aerospike_namespace_index_flash_used_pct{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
     "legendFormat": "Flash"
    },
    {
     "expr": "avg(aerospike_namespace_index_pmem_used_pct{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
     "legendFormat": "PMEM"
    }
   ]
  },
  {
   "title": "Namespace Index (Flash/PMEM) Usage",
   "type": "stat",
   "description": "Namespace index flash usage in bytes\n\nNamespace index PMEM usage in bytes",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(aerospike_namespace_index_flash_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
     "legendFormat": "Flash Used Bytes"
    },
    {
     "expr": "avg(aerospike_namespace_index_pmem_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
     "legendFormat": "PMEM Used Bytes"
    }
   ]
  },
  {
   "title": "Namespace Index (Flash/PMEM) Allocated",
   "type": "stat",
   "description": "Flash Alloc Bytes - Total bytes allocated on the mount(s) for the primary index used by this namespace on this node. This statistic represents entire 4KiB chunks which have at least one element in use.\n\n\nFlash Alloc Percent - Percentage of the mount(s) allocated for the primary index used by this namespace on this node. Calculated as (index_flash_alloc_bytes / index-type.mounts-size-limit) * 100. This statistic represents entire 4KiB chunks which have at least one element in use.",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(aerospike_namespace_index_flash_alloc_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
     "legendFormat": "Flash Alloc Bytes"
    },
    {
     "expr": "avg(aerospike_namespace_index_flash_alloc_pct{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
     "legendFormat": "Flash Alloc Percent %"
    }
   ]
  },
  {
   "title": "NSUP Metrics",
   "type": "stat",
   "description": "Namespace Supervisor (NSUP) Metrics",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(aerospike_namespace_nsup_cycle_duration{cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
     "legendFormat": "Avg Cycle Duration"
    },
    {
     "expr": "max(aerospike_namespace_nsup_cycle_duration{cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
     "legendFormat": "Max Cycle Duration"
    },
    {
     "expr": "avg(aerospike_namespace_nsup_cycle_deleted_pct{cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
     "legendFormat": "% Avg Cycle Deleted"
    },
    {
     "expr": "max(aerospike_namespace_nsup_cycle_deleted_pct{cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
     "legendFormat": "% Max Cycle Deleted"
    }
   ]
  },
  {
   "title": "% Set Quota Used",
   "type": "bargauge",
   "description": "Set Quota usage against \"stop write size\" configuration",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((aerospike_sets_memory_data_bytes{job=\"$job_name\",cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}+aerospike_sets_device_data_bytes{job=\"$job_name\",cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})/(aerospike_sets_stop_writes_size{job=\"$job_name\",cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}!=0))*100)",
     "legendFormat": "{{set}}"
    }
   ]
  },
  {
   "title": "Defrag Sleep",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(aerospike_namespace_storage_engine_defrag_sleep{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
     "legendFormat": "Sleep"
    }
   ]
  },
  {
   "title": "Defrag Low Water Mark",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(aerospike_namespace_storage_engine_defrag_lwm_pct{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
     "legendFormat": "Device Lowe Water Mark"
    }
   ]
  },
  {
   "title": "NSUP Metrics",
   "type": "timeseries",
   "description": "Namespace Supervisor (NSUP) Metrics",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(aerospike_namespace_nsup_cycle_duration{cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}) by (ns)",
     "legendFormat": "Avg Cycle Duration {{ns}}"
    },
    {
     "expr": "max(aerospike_namespace_nsup_cycle_duration{cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}) by (ns)",
     "legendFormat": "Max Cycle Duration {{ns}}"
    }
   ]
  },
  {
   "title": "Defrag Reads & Writes ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(\naerospike_namespace_storage_engine_file_defrag_reads{job=~\"$job_name|$^\", cluster_name=~\"$cluster|$^\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}  \nor \naerospike_namespace_storage_engine_device_defrag_reads{job=~\"$job_name|$^\", cluster_name=~\"$cluster|$^\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}\n)",
     "legendFormat": "{{service}} - Reads"
    },
    {
     "expr": " (\naerospike_namespace_storage_engine_file_defrag_writes{job=~\"$job_name|$^\", cluster_name=~\"$cluster|$^\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}  \nor \naerospike_namespace_storage_engine_device_defrag_writes{job=~\"$job_name|$^\", cluster_name=~\"$cluster|$^\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}\n)",
     "legendFormat": "{{service}} - Writes"
    }
   ]
  },
  {
   "title": "Defrag Q",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(\naerospike_namespace_storage_engine_file_defrag_q{job=~\"$job_name|$^\", cluster_name=~\"$cluster|$^\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}  \nor \naerospike_namespace_storage_engine_device_defrag_q{job=~\"$job_name|$^\", cluster_name=~\"$cluster|$^\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}\n)",
     "legendFormat": "Q"
    }
   ]
  },
  {
   "title": "Throughput (Read, Write)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Client Reads (TPS)",
   "type": "timeseries",
   "description": "Shows per-second average rate of increase in\n\n1. Total reads = client_read_success + client_read_error + client_read_timeout + client_read_not_found + batch_sub_read_success + batch_sub_read_error + batch_sub_read_timeout + batch_sub_read_not_found\n2. Successful reads = client_read_success + batch_sub_read_success\n3. Errored reads = client_read_error + batch_sub_read_error\n4. Timedout reads = client_read_timeout + batch_sub_read_timeout\n5. Not found = client_read_not_found + batch_sub_not_found",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aerospike_namespace_client_read_success{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])+rate(aerospike_namespace_client_read_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])+rate(aerospike_namespace_client_read_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])+rate(aerospike_namespace_client_read_not_found{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_batch_sub_read_success{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_batch_sub_read_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_batch_sub_read_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_batch_sub_read_not_found{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Total"
    },
    {
     "expr": "rate(aerospike_namespace_client_read_success{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_batch_sub_read_success{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Successful"
    },
    {
     "expr": "rate(aerospike_namespace_client_read_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_batch_sub_read_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Error"
    },
    {
     "expr": "rate(aerospike_namespace_client_read_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_batch_sub_read_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Timeout"
    },
    {
     "expr": "rate(aerospike_namespace_client_read_not_found{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_batch_sub_read_not_found{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Not Found"
    }
   ]
  },
  {
   "title": "Client Writes (TPS)",
   "type": "timeseries",
   "description": "Shows per-second average rate of increase in\n\n1. Total writes = client_write_success + client_write_error + client_write_timeout + batch_sub_write_success + batch_sub_write_error + batch_sub_write_timeout\n2. Successful writes = client_write_success + batch_sub_write_success\n3. Errored writes = client_write_error + batch_sub_write_error\n4. Timedout writes = client_write_timeout + batch_sub_write_timeout",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aerospike_namespace_client_write_success{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])+rate(aerospike_namespace_client_write_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])+rate(aerospike_namespace_client_write_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_batch_sub_write_success{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_batch_sub_write_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_batch_sub_write_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Total"
    },
    {
     "expr": "rate(aerospike_namespace_client_write_success{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_batch_sub_write_success{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Successful"
    },
    {
     "expr": "rate(aerospike_namespace_client_write_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_batch_sub_write_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Timeout"
    },
    {
     "expr": "rate(aerospike_namespace_client_write_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_batch_sub_write_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Error"
    }
   ]
  },
  {
   "title": "NSUP Cycle Duration",
   "type": "timeseries",
   "description": "Length of the last NSUP cycle in seconds.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(aerospike_namespace_nsup_cycle_duration{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}) by (service,)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Throughput (Batch, Query, UDF)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Batch Sub Transactions (TPS)",
   "type": "timeseries",
   "description": "Shows per-second average rate of increase in batch transactions",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aerospike_namespace_batch_sub_read_success{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_batch_sub_write_success{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_batch_sub_delete_success{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_batch_sub_udf_complete{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Success"
    },
    {
     "expr": "rate(aerospike_namespace_batch_sub_read_not_found{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_batch_sub_write_not_found{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_batch_sub_delete_not_found{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_batch_sub_udf_not_found{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Not Found"
    },
    {
     "expr": "rate(aerospike_namespace_batch_sub_read_filtered_out{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_batch_sub_write_filtered_out{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_batch_sub_delete_filtered_out{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_batch_sub_udf_filtered_out{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Filtered Out"
    },
    {
     "expr": "rate(aerospike_namespace_batch_sub_read_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_batch_sub_write_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_batch_sub_delete_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_batch_sub_udf_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Error"
    },
    {
     "expr": "rate(aerospike_namespace_batch_sub_read_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_batch_sub_write_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_batch_sub_delete_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_batch_sub_udf_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Timeout"
    }
   ]
  },
  {
   "title": "Queries (TPS)",
   "type": "timeseries",
   "description": "Shows per-second average rate of increase in total queries.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aerospike_namespace_pi_query_long_basic_complete{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_pi_query_short_basic_complete{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_pi_query_aggr_complete{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_pi_query_udf_bg_complete{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_pi_query_ops_bg_complete{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_si_query_long_basic_complete{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_si_query_short_basic_complete{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_si_query_aggr_complete{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_si_query_udf_bg_complete{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_si_query_ops_bg_complete{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Success"
    },
    {
     "expr": "rate(aerospike_namespace_pi_query_long_basic_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_pi_query_short_basic_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_pi_query_aggr_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_pi_query_udf_bg_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_pi_query_ops_bg_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_si_query_long_basic_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_si_query_short_basic_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_si_query_aggr_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_si_query_udf_bg_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_si_query_ops_bg_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Error"
    },
    {
     "expr": "rate(aerospike_namespace_pi_query_long_basic_abort{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_pi_query_short_basic_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_pi_query_aggr_abort{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_pi_query_udf_bg_abort{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_pi_query_ops_bg_abort{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_si_query_long_basic_abort{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_si_query_short_basic_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_si_query_aggr_abort{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_si_query_udf_bg_abort{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_si_query_ops_bg_abort{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Abort/Timeout"
    }
   ]
  },
  {
   "title": "UDFs (TPS)",
   "type": "timeseries",
   "description": "Shows per-second average rate of increase in \n\n1. Total = client_udf_complete + client_udf_timeout + client_udf_error\n2. Successful = client_udf_complete\n3. Error = client_udf_error\n4. Timeout = client_udf_timeout",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aerospike_namespace_client_udf_complete{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])+\nrate(aerospike_namespace_client_udf_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])+\nrate(aerospike_namespace_client_udf_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Total"
    },
    {
     "expr": "rate(aerospike_namespace_client_udf_complete{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Successful"
    },
    {
     "expr": "rate(aerospike_namespace_client_udf_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Error"
    },
    {
     "expr": "rate(aerospike_namespace_client_udf_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Timeout"
    }
   ]
  },
  {
   "title": "Objects",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Master Objects",
   "type": "timeseries",
   "description": "Namespace master objects",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(aerospike_namespace_master_objects{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}) by (service, ns)",
     "legendFormat": "{{service}} {{ns}}"
    }
   ]
  },
  {
   "title": "Prole Objects",
   "type": "timeseries",
   "description": "Namespace replica objects",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(aerospike_namespace_prole_objects{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}) by (service, ns)",
     "legendFormat": "{{service}} {{ns}}"
    }
   ]
  },
  {
   "title": "Non-Replica Objects",
   "type": "timeseries",
   "description": "Namespace non-replica objects",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(aerospike_namespace_non_replica_objects{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}) by (service, ns)",
     "legendFormat": "{{service}} {{ns}}"
    }
   ]
  },
  {
   "title": "Master Tombstones",
   "type": "timeseries",
   "description": "Namespace master tombstones",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(aerospike_namespace_master_tombstones{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}) by (service, ns)",
     "legendFormat": "{{service}} {{ns}}"
    }
   ]
  },
  {
   "title": "Prole Tombstones",
   "type": "timeseries",
   "description": "Namespace replica tombstones",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(aerospike_namespace_prole_tombstones{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}) by (service, ns)",
     "legendFormat": "{{service}} {{ns}}"
    }
   ]
  },
  {
   "title": "Non-Replica Tombstones",
   "type": "timeseries",
   "description": "Namespace non-replica tombstones",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(aerospike_namespace_non_replica_tombstones{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}) by (service, ns)",
     "legendFormat": "{{service}} {{ns}}"
    }
   ]
  },
  {
   "title": "Evicted Objects",
   "type": "timeseries",
   "description": "Namespace evicted objects",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(aerospike_namespace_evicted_objects{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}) by (service, ns)",
     "legendFormat": "{{service}}/{{ns}}"
    }
   ]
  },
  {
   "title": "Expired Objects",
   "type": "timeseries",
   "description": "Namespace expired objects",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(aerospike_namespace_expired_objects{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}) by (service, ns)",
     "legendFormat": "{{service}}/{{ns}}"
    }
   ]
  },
  {
   "title": "Migrations Remaining",
   "type": "timeseries",
   "description": "Namespace migrate_tx_partitions_remaining (transmit) and migrate_rx_partitions_remaining (receive)",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(aerospike_namespace_migrate_tx_partitions_remaining{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}) by (service, ns)",
     "legendFormat": "Outgoing {{service}}/{{ns}}"
    },
    {
     "expr": "sum(aerospike_namespace_migrate_rx_partitions_remaining{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}) by (service, ns)",
     "legendFormat": "Incoming {{service}}/{{ns}}"
    }
   ]
  },
  {
   "title": "XDR Tombstones",
   "type": "timeseries",
   "description": "Number of tombstones which are created by XDR for non-durable client deletes. This includes both master and prole.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(aerospike_namespace_xdr_tombstones{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}) by (service, ns)",
     "legendFormat": "{{service}} {{ns}}"
    }
   ]
  },
  {
   "title": "XDR Bin Cemeteries",
   "type": "timeseries",
   "description": "Number of tombstones with bin-tombstones. They are generated when bin convergence is enabled and a record is durably deleted.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(aerospike_namespace_xdr_bin_cemeteries{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}) by (service, ns)",
     "legendFormat": "{{service}} {{ns}}"
    }
   ]
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 112 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Primary Index Used",
   "type": "timeseries",
   "description": "Namespace Index Usage (Primary Index)",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(aerospike_namespace_memory_used_index_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}) by (service, ns)",
     "legendFormat": "shmem {{service}}/{{ns}}"
    },
    {
     "expr": "sum(aerospike_namespace_index_flash_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}) by (service, ns)",
     "legendFormat": "flash {{service}}/{{ns}}"
    },
    {
     "expr": "sum(aerospike_namespace_index_pmem_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}) by (service, ns)",
     "legendFormat": "pmem {{service}}/{{ns}}"
    }
   ]
  },
  {
   "title": "Secondary Index Used",
   "type": "timeseries",
   "description": "Namespace memory_used_sindex_bytes (Secondary Index)",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(aerospike_namespace_memory_used_sindex_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}) by (service, ns)",
     "legendFormat": "{{service}}/{{ns}}"
    }
   ]
  },
  {
   "title": "Set Index Used",
   "type": "timeseries",
   "description": "Amount of memory occupied by set indexes for this namespace on this node.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(aerospike_namespace_memory_used_set_index_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}) by (service, ns)",
     "legendFormat": "{{service}}/{{ns}}"
    }
   ]
  },
  {
   "title": "Memory Info %",
   "type": "timeseries",
   "description": "Namespace memory_free_pct (available namespace memory percentage), high_water_memory_pct (memory high water mark), stop_writes_pct (stop writes threshold)",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "aerospike_namespace_memory_free_pct{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}",
     "legendFormat": "{{service}}/{{ns}}: Free"
    },
    {
     "expr": "aerospike_namespace_high_water_memory_pct{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}",
     "legendFormat": "{{service}}/{{ns}}: HWM"
    },
    {
     "expr": "aerospike_namespace_stop_writes_pct{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}",
     "legendFormat": "{{service}}/{{ns}}: Stop Writes"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "timeseries",
   "description": "Namespace memory_used_bytes (memory_used_data_bytes (Data) + memory_used_index_bytes (Primary Index) + memory_used_sindex_bytes (Secondary Index))",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "aerospike_namespace_memory_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}",
     "legendFormat": "Used {{service}}/{{ns}}"
    }
   ]
  },
  {
   "title": "Memory Free",
   "type": "timeseries",
   "description": "Namespace free memory = memory_size - memory_used_bytes",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "aerospike_namespace_memory_size{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"} - aerospike_namespace_memory_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}",
     "legendFormat": "{{service}} {{ns}}"
    }
   ]
  },
  {
   "title": "Storage Free %",
   "type": "timeseries",
   "description": "Namespace storage free percentage (device_free_pct or pmem_free_pct)",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "aerospike_namespace_device_free_pct{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}",
     "legendFormat": "device {{service}} {{ns}}"
    },
    {
     "expr": "aerospike_namespace_pmem_free_pct{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}",
     "legendFormat": "pmem {{service}} {{ns}}"
    }
   ]
  },
  {
   "title": "Storage Used",
   "type": "timeseries",
   "description": "Namespace storage usage in bytes (device_used_bytes or pmem_used_bytes)",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "aerospike_namespace_device_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}",
     "legendFormat": "device {{service}} {{ns}}"
    },
    {
     "expr": "aerospike_namespace_pmem_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}",
     "legendFormat": "pmem {{service}} {{ns}}"
    }
   ]
  },
  {
   "title": "Storage Free",
   "type": "timeseries",
   "description": "Namespace storage free bytes (device_total_bytes - device_used_bytes or pmem_total_bytes - pmem_used_bytes)",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "aerospike_namespace_device_total_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"} - aerospike_namespace_device_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}",
     "legendFormat": "device {{service}} {{ns}}"
    },
    {
     "expr": "aerospike_namespace_pmem_total_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"} - aerospike_namespace_pmem_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}",
     "legendFormat": "pmem {{service}} {{ns}}"
    }
   ]
  },
  {
   "title": "Failure Rate",
   "type": "timeseries",
   "description": "Namespace fail_generation (Errors due to generation mismatch), fail_key_busy (Hotkey errors), fail_record_too_big (Errors due to record being more that write block size), fail_xdr_forbidden (Forbidden errors due to XDR configs for incoming XDR traffic)\n\nfail_client_lost_conflict - Number of client write transactions (non-xdr) that failed because some bin's last-update-time is greater than the transaction time. This can happen only when the XDR's bin convergence feature is enabled.\n\nfail_xdr_lost_conflict - Number of XDR write transactions that did not succeed in updating all the attempted bins. Only a subset of bin updates might have failed or all the bin updates might have failed.This can happen only when the XDR's bin convergence feature is enabled.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 137 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aerospike_namespace_fail_generation{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Fail Generation"
    },
    {
     "expr": "rate(aerospike_namespace_fail_key_busy{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Key Busy"
    },
    {
     "expr": "rate(aerospike_namespace_fail_record_too_big{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Record Too Big"
    },
    {
     "expr": "rate(aerospike_namespace_fail_xdr_forbidden{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: XDR Forbidden"
    },
    {
     "expr": "rate(aerospike_namespace_fail_client_lost_conflict{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Client Fail Lost Conflict"
    },
    {
     "expr": "rate(aerospike_namespace_fail_xdr_lost_conflict{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: XDR Fail Lost Conflict"
    }
   ]
  },
  {
   "title": "Batch Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 145 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Batch Sub Reads",
   "type": "timeseries",
   "description": "Shows per-second average rate of increase in batch_sub_read_success, batch_sub_read_not_found, batch_sub_read_error and batch_sub_read_timeout",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 146 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aerospike_namespace_batch_sub_read_success{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Success"
    },
    {
     "expr": "rate(aerospike_namespace_batch_sub_read_not_found{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Not Found"
    },
    {
     "expr": "rate(aerospike_namespace_batch_sub_read_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Error"
    },
    {
     "expr": "rate(aerospike_namespace_batch_sub_read_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Timeout"
    }
   ]
  },
  {
   "title": "Batch Sub Writes",
   "type": "timeseries",
   "description": "Shows per-second average rate of increase in batch_sub_write_success, batch_sub_write_not_found, batch_sub_write_error and batch_sub_write_timeout",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 146 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aerospike_namespace_batch_sub_write_success{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Success"
    },
    {
     "expr": "rate(aerospike_namespace_batch_sub_write_not_found{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Not Found"
    },
    {
     "expr": "rate(aerospike_namespace_batch_sub_write_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Error"
    },
    {
     "expr": "rate(aerospike_namespace_batch_sub_write_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Timeout"
    }
   ]
  },
  {
   "title": "Batch Sub Deletes",
   "type": "timeseries",
   "description": "Shows per-second average rate of increase in batch_sub_delete_success, batch_sub_delete_not_found, batch_sub_delete_error and batch_sub_delete_timeout",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 156 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aerospike_namespace_batch_sub_delete_success{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Success"
    },
    {
     "expr": "rate(aerospike_namespace_batch_sub_delete_not_found{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Not Found"
    },
    {
     "expr": "rate(aerospike_namespace_batch_sub_delete_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Error"
    },
    {
     "expr": "rate(aerospike_namespace_batch_sub_delete_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Timeout"
    }
   ]
  },
  {
   "title": "Batch Sub UDF",
   "type": "timeseries",
   "description": "Shows per-second average rate of increase in batch_sub_udf_success, batch_sub_udf_not_found, batch_sub_udf_error and batch_sub_udf_timeout",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 156 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aerospike_namespace_batch_sub_udf_success{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Success"
    },
    {
     "expr": "rate(aerospike_namespace_batch_sub_udf_not_found{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Not Found"
    },
    {
     "expr": "rate(aerospike_namespace_batch_sub_udf_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Error"
    },
    {
     "expr": "rate(aerospike_namespace_batch_sub_udf_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Timeout"
    }
   ]
  },
  {
   "title": "Batch Sub TSVC",
   "type": "timeseries",
   "description": "Shows per-second average rate of increase in batch_sub_tsvc_error, batch_sub_tsvc_timeout",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 166 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aerospike_namespace_batch_sub_tsvc_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Timeout"
    },
    {
     "expr": "rate(aerospike_namespace_batch_sub_tsvc_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Error"
    }
   ]
  },
  {
   "title": "Pindex Query Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 176 },
   "targets": [
    {}
   ]
  },
  {
   "title": "All PI Queries",
   "type": "timeseries",
   "description": "Shows per-second average rate of increase in primary index queries.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 177 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aerospike_namespace_pi_query_long_basic_complete{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_pi_query_short_basic_complete{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_pi_query_aggr_complete{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_pi_query_udf_bg_complete{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_pi_query_ops_bg_complete{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Success"
    },
    {
     "expr": "rate(aerospike_namespace_pi_query_long_basic_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_pi_query_short_basic_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_pi_query_aggr_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_pi_query_udf_bg_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_pi_query_ops_bg_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Error"
    },
    {
     "expr": "rate(aerospike_namespace_pi_query_long_basic_abort{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_pi_query_short_basic_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_pi_query_aggr_abort{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_pi_query_udf_bg_abort{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_pi_query_ops_bg_abort{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Abort/Timeout"
    }
   ]
  },
  {
   "title": "PI Aggregate Queries",
   "type": "timeseries",
   "description": "Shows per-second average rate of increase in primary index aggregate queries.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 177 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aerospike_namespace_pi_query_aggr_complete{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Success"
    },
    {
     "expr": "rate(aerospike_namespace_pi_query_aggr_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Error"
    },
    {
     "expr": "rate(aerospike_namespace_pi_query_aggr_abort{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Abort"
    }
   ]
  },
  {
   "title": "PI Basic Queries",
   "type": "timeseries",
   "description": "Shows per-second average rate of increase in primary index basic queries.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 187 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aerospike_namespace_pi_query_long_basic_complete{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_pi_query_short_basic_complete{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Success"
    },
    {
     "expr": "rate(aerospike_namespace_pi_query_long_basic_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_pi_query_short_basic_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Error"
    },
    {
     "expr": "rate(aerospike_namespace_pi_query_long_basic_abort{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_pi_query_short_basic_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Abort/Timeout"
    }
   ]
  },
  {
   "title": "PI OPS BG Queries",
   "type": "timeseries",
   "description": "Shows per-second average rate of increase in primary background OPs queries.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 187 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aerospike_namespace_pi_query_ops_bg_complete{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Success"
    },
    {
     "expr": "rate(aerospike_namespace_pi_query_ops_bg_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Error"
    },
    {
     "expr": "rate(aerospike_namespace_pi_query_ops_bg_abort{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Abort/Timeout"
    }
   ]
  },
  {
   "title": "PI Basic Short Queries",
   "type": "timeseries",
   "description": "Shows per-second average rate of increase in primary index basic short queries.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 197 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aerospike_namespace_pi_query_short_basic_complete{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Success"
    },
    {
     "expr": "rate(aerospike_namespace_pi_query_short_basic_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Error"
    },
    {
     "expr": "rate(aerospike_namespace_pi_query_short_basic_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Timeout"
    }
   ]
  },
  {
   "title": "PI UDF BG Queries",
   "type": "timeseries",
   "description": "Shows per-second average rate of increase in primary index background UDF queries.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 197 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aerospike_namespace_pi_query_udf_bg_complete{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Success"
    },
    {
     "expr": "rate(aerospike_namespace_pi_query_udf_bg_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Error"
    },
    {
     "expr": "rate(aerospike_namespace_pi_query_udf_bg_abort{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Abort/Timeout"
    }
   ]
  },
  {
   "title": "PI Basic Long Queries",
   "type": "timeseries",
   "description": "Shows per-second average rate of increase in primary index basic long queries.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 207 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aerospike_namespace_pi_query_long_basic_complete{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Success"
    },
    {
     "expr": "rate(aerospike_namespace_pi_query_long_basic_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Error"
    },
    {
     "expr": "rate(aerospike_namespace_pi_query_long_basic_abort{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Abort"
    }
   ]
  },
  {
   "title": "Sindex Query Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 217 },
   "targets": [
    {}
   ]
  },
  {
   "title": "All SI Queries",
   "type": "timeseries",
   "description": "Shows per-second average rate of increase in secondary index queries.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 218 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aerospike_namespace_si_query_long_basic_complete{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_si_query_short_basic_complete{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_si_query_aggr_complete{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_si_query_udf_bg_complete{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_si_query_ops_bg_complete{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Success"
    },
    {
     "expr": "rate(aerospike_namespace_si_query_long_basic_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_si_query_short_basic_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_si_query_aggr_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_si_query_udf_bg_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_si_query_ops_bg_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Error"
    },
    {
     "expr": "rate(aerospike_namespace_si_query_long_basic_abort{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_si_query_short_basic_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_si_query_aggr_abort{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_si_query_udf_bg_abort{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_si_query_ops_bg_abort{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Abort/Timeout"
    }
   ]
  },
  {
   "title": "SI Aggregate Queries",
   "type": "timeseries",
   "description": "Shows per-second average rate of increase in secondary index aggregate queries.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 218 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aerospike_namespace_si_query_aggr_complete{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Success"
    },
    {
     "expr": "rate(aerospike_namespace_si_query_aggr_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Error"
    },
    {
     "expr": "rate(aerospike_namespace_si_query_aggr_abort{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Abort"
    }
   ]
  },
  {
   "title": "SI Basic Queries",
   "type": "timeseries",
   "description": "Shows per-second average rate of increase in secondary index basic queries.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 228 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aerospike_namespace_si_query_long_basic_complete{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_si_query_short_basic_complete{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Success"
    },
    {
     "expr": "rate(aerospike_namespace_si_query_long_basic_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_si_query_short_basic_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Error"
    },
    {
     "expr": "rate(aerospike_namespace_si_query_long_basic_abort{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_si_query_short_basic_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Abort/Timeout"
    }
   ]
  },
  {
   "title": "SI UDF BG Queries",
   "type": "timeseries",
   "description": "Shows per-second average rate of increase in secondary index background UDF queries.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 228 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aerospike_namespace_si_query_udf_bg_complete{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Success"
    },
    {
     "expr": "rate(aerospike_namespace_si_query_udf_bg_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Error"
    },
    {
     "expr": "rate(aerospike_namespace_si_query_udf_bg_abort{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Abort"
    }
   ]
  },
  {
   "title": "SI Basic Short Queries",
   "type": "timeseries",
   "description": "Shows per-second average rate of increase in secondary index basic short queries.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 238 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aerospike_namespace_si_query_short_basic_complete{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Success"
    },
    {
     "expr": "rate(aerospike_namespace_si_query_short_basic_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Error"
    },
    {
     "expr": "rate(aerospike_namespace_si_query_short_basic_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Timeout"
    }
   ]
  },
  {
   "title": "SI OPS BG Queries",
   "type": "timeseries",
   "description": "Shows per-second average rate of increase in secondary index background OPs queries.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 238 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aerospike_namespace_si_query_ops_bg_complete{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Success"
    },
    {
     "expr": "rate(aerospike_namespace_si_query_ops_bg_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Error"
    },
    {
     "expr": "rate(aerospike_namespace_si_query_ops_bg_abort{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Abort"
    }
   ]
  },
  {
   "title": "SI Basic Long Queries",
   "type": "timeseries",
   "description": "Shows per-second average rate of increase in secondary index basic long queries.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 248 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aerospike_namespace_si_query_long_basic_complete{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Success"
    },
    {
     "expr": "rate(aerospike_namespace_si_query_long_basic_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Error"
    },
    {
     "expr": "rate(aerospike_namespace_si_query_long_basic_abort{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])",
     "legendFormat": "{{service}}/{{ns}}: Abort"
    }
   ]
  },
  {
   "title": "Sindex Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 258 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Sindex GC Cleaned",
   "type": "timeseries",
   "description": "Shows per-second average rate of increase in secondary index garbage collection.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 259 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(aerospike_namespace_sindex_gc_cleaned{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])) by (job,cluster_name,ns)",
     "legendFormat": "{{ns}}: "
    }
   ]
  }
 ]
}