apiVersion: teranode.bsvblockchain.org/v1alpha1
kind: Cluster
metadata:
  name: teranode
spec:
  asset:
    enabled: false
    spec:
      deploymentOverrides:
        nodeSelector:
          role: node-selector
        replicas: 1
        resources: {}
        tolerations:
        - effect: NoSchedule
          key: role
          operator: Equal
          value: node-selector
      grpcIngress:
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: ast-grpc
        className: traefik-internal
        host: domain
      httpIngress:
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: web
        className: traefik-internal
        host: domain
      httpsIngress:
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
        className: traefik-internal
        host: domain
  blockAssembly:
    enabled: false
    spec:
      deploymentOverrides:
        nodeSelector:
          role: node-selector
        replicas: 1
        resources: {}
        tolerations:
        - effect: NoSchedule
          key: role
          operator: Equal
          value: node-selector
  blockPersister:
    enabled: false
    spec:
      deploymentOverrides:
        nodeSelector:
          role: node-selector
        replicas: 1
        resources: {}
        tolerations:
        - effect: NoSchedule
          key: role
          operator: Equal
          value: node-selector
      storageClass: fsx-lustre
      storageResources:
        requests:
          storage: 5Gi
  blockValidator:
    enabled: false
    spec:
      deploymentOverrides:
        nodeSelector:
          role: node-selector
        replicas: 1
        resources: {}
        tolerations:
        - effect: NoSchedule
          key: role
          operator: Equal
          value: node-selector
  blockchain:
    enabled: false
    spec:
      deploymentOverrides:
        nodeSelector:
          role: node-selector
        replicas: 1
        resources: {}
        tolerations:
        - effect: NoSchedule
          key: role
          operator: Equal
          value: node-selector
  bootstrap:
    enabled: false
    spec: {}
  coinbase:
    enabled: false
    spec:
      deploymentOverrides:
        nodeSelector:
          role: node-selector
        replicas: 1
        resources: {}
        tolerations:
        - effect: NoSchedule
          key: role
          operator: Equal
          value: node-selector
  configMapName: shared-config
  image: image:latest
  legacy:
    enabled: false
    spec:
      deploymentOverrides:
        configMapName: legacy-config
        nodeSelector:
          role: node-selector
        replicas: 1
        resources: {}
        tolerations:
        - effect: NoSchedule
          key: role
          operator: Equal
          value: node-selector
  miner:
    enabled: false
    spec:
      deploymentOverrides:
        nodeSelector:
          role: node-selector
        replicas: 1
        resources: {}
        tolerations:
        - effect: NoSchedule
          key: role
          operator: Equal
          value: node-selector
  peer:
    enabled: false
    spec:
      deploymentOverrides:
        nodeSelector:
          role: node-selector
        replicas: 1
        resources: {}
        tolerations:
        - effect: NoSchedule
          key: role
          operator: Equal
          value: node-selector
      grpcIngress:
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: peer-grpc
        className: traefik-internal
        host: domain
      wsIngress:
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: p2p-ws
        className: traefik-internal
        host: domain
      wssIngress:
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: p2p-wss
        className: traefik-internal
        host: domain
  propagation:
    enabled: false
    spec:
      deploymentOverrides:
        nodeSelector:
          role: node-selector
        replicas: 1
        resources: {}
        tolerations:
        - effect: NoSchedule
          key: role
          operator: Equal
          value: node-selector
      grpcIngress:
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: prop-grpc
        className: traefik-internal
        host: domain
      serviceAnnotations:
        traefik.ingress.kubernetes.io/service.serversscheme: h2c
  subtreeValidator:
    enabled: false
    spec:
      deploymentOverrides:
        nodeSelector:
          role: node-selector
        replicas: 1
        resources: {}
        tolerations:
        - effect: NoSchedule
          key: role
          operator: Equal
          value: node-selector
      storageClass: fsx-lustre
      storageResources:
        requests:
          storage: 3600Gi
  utxoPersister:
    enabled: false
    spec:
      deploymentOverrides:
        nodeSelector:
          role: node-selector
        replicas: 1
        resources: {}
        tolerations:
        - effect: NoSchedule
          key: role
          operator: Equal
          value: node-selector
  validator:
    enabled: false
    spec: {}
