global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'teranode'
    static_configs:
      - targets: ['teranode-blockchain:9091', 'teranode-asset:9091', 'teranode-coinbase:9091', 'teranode-miner:9091', 'teranode-rpc:9091', 'teranode-p2p:9091', 'teranode-subtreevalidation:9091', 'teranode-blockvalidation:9091', 'teranode-blockassembly:9091', 'teranode-blockpersister:9091', 'teranode-propagation:9091']
