apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: root-volume
  namespace: regtest
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: default
