apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: regtest
  namespace: regtest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: regtest
  serviceName: regtest
  template:
    metadata:
      labels:
        app: regtest
    spec:
      containers:
        - name: regtest
          image: eu.gcr.io/ubsv-383015/bitcoin-regtest:1.0.14
          ports:
            - containerPort: 18332
              protocol: TCP
            - containerPort: 18333
              protocol: TCP
            - containerPort: 28332
              protocol: TCP
          resources:
            requests:
              memory: 2Gi
              cpu: "0.2"
            limits:
              memory: 4Gi
              cpu: "1"
          volumeMounts:
            - name: root-volume
              mountPath: /bitcoin
      volumes:
        - name: root-volume
          emptyDir:
            sizeLimit: 10Gi
  volumeClaimTemplates:
    - metadata:
        name: root-volume
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: regtest
  namespace: regtest
  labels:
    app: regtest
spec:
  selector:
    app: regtest
  ports:
    - name: rpc
      port: 18332
      targetPort: 18332
      protocol: TCP
    - name: zmq
      port: 28332
      targetPort: 28332
      protocol: TCP
    - name: p2p
      port: 18333
      targetPort: 18333
      protocol: TCP