apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  labels:
    io.kompose.service: postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgres
  template:
    metadata:
      labels:
        io.kompose.service: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_PASSWORD
              value: really_strong_password_change_me
            - name: POSTGRES_USER
              value: postgres
          ports:
            - containerPort: 5432
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
            failureThreshold: 5
            periodSeconds: 5
            timeoutSeconds: 5
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d/init.sql
              name: postgres-cm0
              subPath: init.sql
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
      volumes:
        - name: postgres-cm0
          configMap:
            name: postgres-cm0
            items:
              - key: init.sql
                path: init.sql
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
