apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod-teranet-1

configMapGenerator:
  - literals:
      - SETTINGS_CONTEXT=operator.testing.t1
      - asset_centrifuge_disable=true
      - blockassembly_disabled=true
    name: shared-config
    behavior: merge

namePrefix: teranet-1-

patches:
  - path: node-selector-patch.yaml
    target:
      kind: Cluster
  - path: host-patch.yaml
    target:
      kind: Cluster
  - path: resources-patch.yaml
    target:
      kind: Cluster
  - path: enabled-services-patch.yaml
    target:
      kind: Cluster


resources:
  - ../../base
