name: test-build-deploy
on:
  push:
    tags:
      - 'v*'
      - 'scaling-v*'
    branches:
      - jeff-multiarch
      # - master
      # - staging

env:
  # These variables aren't used for called reusable workflows, so we have to also define 'with' variables below
  REPO: ubsv
  ECR_REGION: eu-north-1

jobs:
  # Get version tag
  get_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Determine deployment tag
        id: deployment_tag
        run: |
          if [[ '${{ github.ref_type }}' == 'tag' ]]; then
            export tag=${{ github.ref_name }}
            echo "version tag is $tag"
            echo "id=$tag" >> $GITHUB_OUTPUT
          else
            export tag=${{ github.sha }}
            echo "version tag is $tag"
            echo "id=$tag" >> $GITHUB_OUTPUT
          fi
    outputs:
      deployment_tag: ${{ steps.deployment_tag.outputs.id }}
  # Tests and code lint
  test_and_lint:
    uses: ./.github/workflows/gke_tests.yaml
    secrets: inherit
  # Build for X86 (AMD64)
  build_amd64:
    needs: [test_and_lint, get_tag]
    uses: ./.github/workflows/gke_build.yaml
    secrets: inherit
    with:
      arch: amd64
      repo: ubsv
      tag: ${{ needs.get_tag.outputs.deployment_tag }}
      region: eu-north-1
  # Build for ARM64 (Graviton and Darwin)
  build_arm64:
    needs: [test_and_lint, get_tag]
    uses: ./.github/workflows/gke_build.yaml
    secrets: inherit
    with:
      arch: arm64
      repo: ubsv
      tag: ${{ needs.get_tag.outputs.deployment_tag }}
      region: eu-north-1
  # Create docker manifest for multiple architecture tags
  create_manifest:
    needs: [build_amd64, build_arm64, get_tag]
    uses: ./.github/workflows/gke_manifest.yaml
    secrets: inherit
    with:
      region: eu-north-1
      repo: ubsv
      tag: ${{ needs.get_tag.outputs.deployment_tag }}
  deploy:
    needs: [create_manifest, get_tag]
    uses: ./.github/workflows/gke_deploy.yaml
    secrets: inherit
    with:
      repo: ubsv
      tag: ${{ needs.get_tag.outputs.deployment_tag }}
