name: test-build-deploy
on:
  push:
    tags:
      - 'v*'
    branches:
      - main
      - staging
      - release/*

env:
  # These variables aren't used for called reusable workflows, so we have to also define 'with' variables below
  REPO: teranode
  ECR_REGION: eu-north-1

jobs:
  # Get version tag
  get_tag:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Determine deployment tag
        id: deployment_tag
        run: |
          if [[ '${{ github.ref_type }}' == 'tag' ]]; then
            export tag=${{ github.ref_name }}
            echo "version tag is $tag"
            echo "id=$tag" >> $GITHUB_OUTPUT
          else
            export tag=${{ github.sha }}
            echo "version tag is $tag"
            echo "id=$tag" >> $GITHUB_OUTPUT
          fi
    outputs:
      deployment_tag: ${{ steps.deployment_tag.outputs.id }}
  
  # Tests and code lint
  test_and_lint:
    uses: ./.github/workflows/gke_tests.yaml
    secrets: inherit

  # Build for X86 (AMD64)
  build_amd64:
    needs: [ get_tag ]
    uses: ./.github/workflows/gke_build.yaml
    secrets: inherit
    with:
      arch: amd64
      repo: teranode
      tag: ${{ needs.get_tag.outputs.deployment_tag }}
      region: eu-north-1
  
  # Build for ARM64 (Graviton and Darwin)
  build_arm64:
    needs: [ get_tag ]
    uses: ./.github/workflows/gke_build.yaml
    secrets: inherit
    with:
      arch: arm64
      repo: teranode
      tag: ${{ needs.get_tag.outputs.deployment_tag }}
      region: eu-north-1
  
  # Create docker manifest for multiple architecture tags
  create_manifest:
    needs: [ test_and_lint, build_amd64, build_arm64, get_tag ]
    uses: ./.github/workflows/gke_manifest.yaml
    secrets: inherit
    with:
      repo: teranode
      tag: ${{ needs.get_tag.outputs.deployment_tag }}
      region: eu-north-1

  # Operations team notifications
  notify_on_failure:
    runs-on: ubuntu-latest
    if: always()
    needs:
      - test_and_lint
      - build_amd64
      - build_arm64
      - create_manifest
    timeout-minutes: 15
    steps:
      - name: Notify on failure
        if: ${{ contains(needs.*.result, 'failure') }}
        run: |
          echo "Deployment failed"
          curl -X POST https://hooks.slack.com/triggers/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 \
          -H "Content-Type: application/json" \
          -d '{
            "repo": "${{ github.repository }}",
            "commit": "${{ github.sha }}",
            "build_number": "${{ github.run_id }}",
            "link": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
          }'

  # Run long tests in a separate job
  trigger-long-tests:
    runs-on: teranode-runner
    if: always()
    needs:
      - build_amd64
      - build_arm64
      - create_manifest
    steps:
      - name: Trigger Long Tests
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'long_tests.yaml',
              ref: '${{ github.ref_name }}',
              inputs: {
                run_id: '${{ github.run_id }}-${{ github.sha }}'
              }
            });
