name: build-manifest
on:
  workflow_call:
    inputs:
      repo:
        description: 'Repo name'
        required: true
        type: string
      tag:
        description: 'Deployment tag'
        required: true
        type: string
      region:
        description: 'AWS region'
        required: true
        type: string
      pull_request:
        description: 'Is this a pull request?'
        required: false
        type: boolean
        default: false

jobs:
  build_manifest:
    name: Deploy EKS
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      registry: ${{ steps.login-ecr.outputs.registry }}
    steps:

      # Set up AWS CLI
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.region }}

      # Authenticate Docker to AWS ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: true

      - name: Deployment message
        run: echo "Deploying Manifest for tag ${{ inputs.tag }}"

      # Set latest tag if not a pull request
      - name: Set latest tag
        id: latest
        run: |
          case ${{ inputs.pull_request }} in
            "false")
            echo "tag=${{ steps.login-ecr.outputs.registry }}/${{ inputs.repo }}:latest" >> $GITHUB_OUTPUT
            ;;
          esac

      # Create docker manifest
      - uses: int128/docker-manifest-create-action@v2
        with:
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/${{ inputs.repo }}:${{ inputs.tag }}
            ${{ steps.latest.outputs.tag }}
          sources: |
            ${{ steps.login-ecr.outputs.registry }}/${{ inputs.repo }}:${{ github.sha }}-amd64
            ${{ steps.login-ecr.outputs.registry }}/${{ inputs.repo }}:${{ github.sha }}-arm64
