name: deploy-eks
on:
  workflow_call:
    inputs:
      repo:
        description: 'Repo name'
        required: true
        type: string
      tag:
        description: 'Deployment tag'
        required: true
        type: string
env:
  # Must be set here because re-usable workflows don't seem to pass variables conveniently enough
  ECR_URL: 434394763103.dkr.ecr.eu-north-1.amazonaws.com

jobs:
  send_msg:
    name: Deploy EKS
    runs-on: self-hosted
    steps:
      - name: tag
        run: echo "Image repo/tag is ${{ env.ECR_URL }}/${{ inputs.repo }}:${{ inputs.tag }}"
      - name: ref
        run: echo "Github Event Ref is ${{ github.event.ref }}"

  eks-deploy-eu-testing:
    uses: ./.github/workflows/deploy-to-region.yaml
    secrets: inherit
    if: startsWith(github.event.ref, 'refs/tags/v')
    with:
      region: eu-central-1
      ubsv_env: testing
