name: deploy-eks
on:
  workflow_call:
    inputs:
      repo:
        description: 'Repo name'
        required: true
        type: string
      tag:
        description: 'Deployment tag'
        required: true
        type: string
env:
  # Must be set here because re-usable workflows don't seem to pass variables conveniently enough
  ECR_URL: 434394763103.dkr.ecr.eu-north-1.amazonaws.com

jobs:
  send_msg:
    name: Deploy EKS
    runs-on: self-hosted
    steps:
      - name: tag
        run: echo "Image repo/tag is ${{ env.ECR_URL }}/${{ inputs.repo }}:${{ inputs.tag }}"
      - name: ref
        run: echo "Github Event Ref is ${{ github.event.ref }}"

  eks-deploy-eu-testing:
    uses: ./.github/workflows/deploy-to-region.yaml
    secrets: inherit
    if: startsWith(github.event.ref, 'refs/tags/v')
    with:
      region: eu-central-1
      ubsv_env: testing

#  eks-deploy-eu-allinone:
#    uses: ./.github/workflows/deploy-to-region.yaml
#    secrets: inherit
#    if: startsWith(github.event.ref, 'refs/tags/v')
#    with:
#      region: eu-west-1
#      ubsv_env: allinone

  eks-deploy-eu-scaling:
    uses: ./.github/workflows/deploy-to-region.yaml
    secrets: inherit
    if: startsWith(github.event.ref, 'refs/tags/scaling-v')
    with:
      region: eu-west-1
      ubsv_env: scaling

  eks-deploy-us-scaling:
    uses: ./.github/workflows/deploy-to-region.yaml
    secrets: inherit
    if: startsWith(github.event.ref, 'refs/tags/scaling-v')
    with:
      region: us-east-1
      ubsv_env: scaling

  eks-deploy-asia-scaling:
    uses: ./.github/workflows/deploy-to-region.yaml
    secrets: inherit
    if: startsWith(github.event.ref, 'refs/tags/scaling-v')
    with:
      region: ap-south-1
      ubsv_env: scaling

  eks-deploy-usw-scaling:
    uses: ./.github/workflows/deploy-to-region.yaml
    secrets: inherit
    if: startsWith(github.event.ref, 'refs/tags/scaling-v')
    with:
      region: us-west-2
      ubsv_env: scaling

  eks-deploy-cc1-scaling:
    uses: ./.github/workflows/deploy-to-region.yaml
    secrets: inherit
    if: startsWith(github.event.ref, 'refs/tags/scaling-v')
    with:
      region: ca-central-1
      ubsv_env: scaling

  eks-deploy-ane-scaling:
    uses: ./.github/workflows/deploy-to-region.yaml
    secrets: inherit
    if: startsWith(github.event.ref, 'refs/tags/scaling-v')
    with:
      region: ap-northeast-2
      ubsv_env: scaling