name: tests
on:
  workflow_call

jobs:
  go-lint-and-test:
    name: Go Lint and Test
    runs-on: self-hosted
    strategy: # This will cause the workflow to terminate if any job fails
      fail-fast: true
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5 # v4 has caching enabled by default
        with:
          go-version: '1.22.3'

      #      - name: Install deps and lint deps
      #        run: make install-lint
      #
      #      - name: Run golangci-lint
      #        run: make lint

      - name: Run Go tests
        run: make longtests
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.out
          retention-days: 1

  sonarqube:
    name: Sonarqube
    runs-on: self-hosted
    needs: go-lint-and-test
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: coverage-report

    # Re-run golangci separately without exiting on errors and generating a report for use in Sonar
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v5
      with:
        version: latest
        args: --timeout=5m --issues-exit-code=0 --out-format=checkstyle:golangci-lint-report.xml

    - uses: twingate/github-action@4493ffc3806241aa98194a3fa679f874bce013b5
      with:
        service-key: ${{ secrets.TWINGATE_GH_ACTIONS_SERVICE_KEY }} # Required

    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@v2.0.2
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: https://sonarqube.ubsv.dev
      continue-on-error: true

    - name: SonarQube Quality Gate check
      uses: sonarsource/sonarqube-quality-gate-action@master
      timeout-minutes: 10
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: https://sonarqube.ubsv.dev
      continue-on-error: true
