name: deploy-eks
on:
  workflow_call:
    inputs:
      repo:
        description: 'Repo name'
        required: true
        type: string
      tag:
        description: 'Deployment tag'
        required: true
        type: string
env:
  # Must be set here because re-usable workflows don't seem to pass variables conveniently enough
  ECR_URL: 434394763103.dkr.ecr.eu-north-1.amazonaws.com

jobs:
  send_msg:
    name: Deploy EKS
    runs-on: ubuntu-latest
    steps:
      - name: tag
        run: echo "Image repo/tag is ${{ env.ECR_URL }}/${{ inputs.repo }}:${{ inputs.tag }}"
      - name: ref
        run: echo "Github Event Ref is ${{ github.event.ref }}"

  eks-deploy-eu-allinone:
    uses: ./.github/workflows/deploy-to-region.yaml
    secrets: inherit
    if: startsWith(github.event.ref, 'refs/tags/v')
    with:
      region: eu-west-1
      ubsv_env: allinone

  eks-deploy-eu-scaling:
    uses: ./.github/workflows/deploy-to-region.yaml
    secrets: inherit
    if: startsWith(github.event.ref, 'refs/tags/scaling-v')
    with:
      region: eu-west-1
      ubsv_env: scaling

  eks-deploy-us-allinone:
    uses: ./.github/workflows/deploy-to-region.yaml
    secrets: inherit
    if: startsWith(github.event.ref, 'refs/tags/v')
    with:
      region: us-east-1
      ubsv_env: allinone

  eks-deploy-us-scaling:
    uses: ./.github/workflows/deploy-to-region.yaml
    secrets: inherit
    if: startsWith(github.event.ref, 'refs/tags/scaling-v')
    with:
      region: us-east-1
      ubsv_env: scaling

  # eks-deploy-asia-allinone:
    # uses: ./.github/workflows/deploy-to-region.yaml
    # secrets: inherit
    # if: startsWith(github.event.ref, 'refs/tags/v')
    # with:
      # region: ap-northeast-1
      # ubsv_env: allinone

  # eks-deploy-asia-scaling:
    # uses: ./.github/workflows/deploy-to-region.yaml
    # secrets: inherit
    # if: startsWith(github.event.ref, 'refs/tags/scaling-v')
    # with:
      # region: ap-northeast-1
      # ubsv_env: scaling
