name: long-tests-by-category
on:
  schedule:
    - cron: "0 1 * * *" # Runs at 1 AM UTC every day (offset from other nightly tests)
  workflow_dispatch:

env:
  REPO: teranode
  SETTINGS_CONTEXT_DEFAULT: "test"

jobs:
  test-services:
    runs-on: teranode-runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21.0"
          cache: "false"

      - name: Run Services Tests
        run: |
          cd test/services && \
          go test -v -count 1 -tags test_services ./...
        env:
          settings_context: ${{ env.SETTINGS_CONTEXT_DEFAULT }}
        continue-on-error: false

  test-model:
    runs-on: teranode-runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21.0"
          cache: "false"

      - name: Run Model Tests
        run: |
          cd test/model && \
          go test -v -count 1 -tags test_model ./...
        env:
          settings_context: ${{ env.SETTINGS_CONTEXT_DEFAULT }}
        continue-on-error: false

  test-stores:
    runs-on: teranode-runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21.0"
          cache: "false"

      - name: Run Stores Tests
        run: |
          cd test/stores && \
          go test -v -count 1 -tags test_stores ./...
        env:
          settings_context: ${{ env.SETTINGS_CONTEXT_DEFAULT }}
        continue-on-error: false

  test-util:
    runs-on: teranode-runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21.0"
          cache: "false"

      - name: Run Util Tests
        run: |
          cd test/util && \
          go test -v -count 1 -tags test_util ./...
        env:
          settings_context: ${{ env.SETTINGS_CONTEXT_DEFAULT }}
        continue-on-error: false
