name: nightly-test-runs
on:
  schedule:
    - cron: "0 0 * * *" # Runs at midnight UTC every day
  workflow_dispatch:

env:
  REPO: teranode
  ECR_REGION: eu-north-1
  SETTINGS_CONTEXT_DEFAULT: "default_context"
  USE_ECR_IMAGE: true

jobs:
  pull-image:
    runs-on: teranode-runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.ECR_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: true

      - name: Pull Docker Image from ECR (if USE_ECR_IMAGE=true)
        if: env.USE_ECR_IMAGE == 'true'
        run: |
          IMAGE_TAG=latest
          docker pull ${{ steps.login-ecr.outputs.registry }}/${{ env.REPO }}:$IMAGE_TAG
          docker tag ${{ steps.login-ecr.outputs.registry }}/${{ env.REPO }}:$IMAGE_TAG teranode:latest

  run-tests:
    needs: pull-image
    runs-on: teranode-runner
    strategy:
      matrix:
        test_config:
          # TNC Tests
          - test_dir: "test/tnc"
            test_tags: "test_tnc"
            test_suite: "TestTNC1_1TestSuite"
            test_func: "TestVerifyMerkleRootCalculation"
          - test_dir: "test/tnc"
            test_tags: "test_tnc"
            test_suite: "TestTNC1_2TestSuite"
            test_func: "TestCheckPrevBlockHash"
          - test_dir: "test/tnc"
            test_tags: "test_tnc"
            test_suite: "TestTNC1_2TestSuite"
            test_func: "TestPrevBlockHashAfterReorg"
          - test_dir: "test/tnc"
            test_tags: "test_tnc"
            test_suite: "TestTNC1TestSuite"
            test_func: "TestCandidateContainsAllTxs"
          - test_dir: "test/tnc"
            test_tags: "test_tnc"
            test_suite: "TestTNC1TestSuite"
            test_func: "TestCheckHashPrevBlockCandidate"
          - test_dir: "test/tnc"
            test_tags: "test_tnc"
            test_suite: "TestTNC1TestSuite"
            test_func: "TestCoinbaseTXAmount"
          - test_dir: "test/tnc"
            test_tags: "test_tnc"
            test_suite: "TestTNC1TestSuite"
            test_func: "TestCoinbaseTXAmount2"
          - test_dir: "test/tnc"
            test_tags: "test_tnc"
            test_suite: "TestTNC2_1TestSuite"
            test_func: "TestUniqueCandidateIdentifiers"
          - test_dir: "test/tnc"
            test_tags: "test_tnc"
            test_suite: "TestTNC2_1TestSuite"
            test_func: "TestConcurrentCandidateIdentifiers"
          - test_dir: "test/tnc"
            test_tags: "test_tnc"
            test_suite: "TestTNC2_2TestSuite"
            test_func: "TestCandidateBlockStorage"
          - test_dir: "test/tnc"
            test_tags: "test_tnc"
            test_suite: "TestTNC2_2TestSuite"
            test_func: "TestCandidateBlockRetention"
          - test_dir: "test/tnc"
            test_tags: "test_tnc"
            test_suite: "TestTNC2_2TestSuite"
            test_func: "TestConcurrentCandidateStorage"

          # TNB Tests
          - test_dir: "test/tnb"
            test_tags: "test_tnb"
            test_suite: "TestTNB1TestSuite"
            test_func: "TestSendTxsInBatch"
          - test_dir: "test/tnb"
            test_tags: "test_tnb"
            test_suite: "TestTNB1TestSuite"
            test_func: "TestReceiveExtendedFormatTx"
          - test_dir: "test/tnb"
            test_tags: "test_tnb"
            test_suite: "TestTNB1TestSuite"
            test_func: "TestNoReformattingRequired"
          - test_dir: "test/tnb"
            test_tags: "test_tnb"
            test_suite: "TestTNB2TestSuite"
            test_func: "TestUTXOValidation"
          - test_dir: "test/tnb"
            test_tags: "test_tnb"
            test_suite: "TestTNB2TestSuite"
            test_func: "TestScriptValidation"
          - test_dir: "test/tnb"
            test_tags: "test_tnb"
            test_suite: "TestTNB6TestSuite"
            test_func: "TestUTXOSetManagement"

          # TNJ Tests
          - test_dir: "test/tnj"
            test_tags: "test_tnj"
            test_suite: "TestTNJLockTimeTestSuite"
            test_func: "TestLocktimeScenarios"
          - test_dir: "test/tnj"
            test_tags: "test_tnj"
            test_suite: "TestTNJ4TestSuite"
            test_func: "TestBlockSubsidy"
          - test_dir: "test/tnj"
            test_tags: "test_tnj"
            test_suite: "TestTNJDoubleSpendTestSuite"
            test_func: "TestRejectLongerChainWithDoubleSpend"
          - test_dir: "test/tnj"
            test_tags: "test_tnj"
            test_suite: "TestTNJDoubleSpendTestSuite"
            test_func: "TestDoubleSpendMultipleUtxos"

          # TND Tests
          - test_dir: "test/tnd"
            test_tags: "test_tnd"
            test_suite: "TestTND1_1TestSuite"
            test_func: "TestBlockPropagation"
          - test_dir: "test/tnd"
            test_tags: "test_tnd"
            test_suite: "TestTND1_1TestSuite"
            test_func: "TestBlockPropagationWithNotifications"

          # TNE Tests
          - test_dir: "test/tne"
            test_tags: "test_tne"
            test_suite: "TestTNE1_1TestSuite"
            test_func: "TestNode_DoNotVerifyTransactionsIfAlreadyVerified"

          # TNA Tests
          - test_dir: "test/tna"
            test_tags: "test_tna"
            test_suite: "TNA1TestSuite"
            test_func: "TestBroadcastNewTxAllNodes"
          - test_dir: "test/tna"
            test_tags: "test_tna"
            test_suite: "TNA2TestSuite"
            test_func: "TestTxsReceivedAllNodes"
          - test_dir: "test/tna"
            test_tags: "test_tna"
            test_suite: "TestTNA4TestSuite"
            test_func: "TestBlockBroadcast"
          - test_dir: "test/tna"
            test_tags: "test_tna"
            test_suite: "TestTNA6TestSuite"
            test_func: "TestAcceptanceNextBlock"

          # FSM Tests
          - test_dir: "test/fsm"
            test_tags: "test_fsm"
            test_suite: "TestFsmTestSuite"
            test_func: "TestNodeCatchUpState_WithStartAndStopNodes"
          - test_dir: "test/fsm"
            test_tags: "test_fsm"
            test_suite: "TestFsmTestSuite"
            test_func: "TestNodeCatchUpStateSingleNode_WithP2PSwitch"
          - test_dir: "test/fsm"
            test_tags: "test_fsm"
            test_suite: "TestFsmTestSuite"
            test_func: "TestNodeCatchUpStateMultipleNodes_WithP2PSwitch"
          - test_dir: "test/fsm"
            test_tags: "test_fsm"
            test_suite: "TestFsmTestSuite"
            test_func: "TestNodeDoesNotSendMiningCandidate_CatchUpState_WithStartAndStopNodes"

      max-parallel: 1
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.ECR_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - uses: actions/setup-go@v5
        with:
          go-version: "1.21.0"
          cache: "false"

      - name: Run Test
        run: |
          go clean -testcache
          docker pull ${{ steps.login-ecr.outputs.registry }}/${{ env.REPO }}:latest
          docker tag ${{ steps.login-ecr.outputs.registry }}/${{ env.REPO }}:latest teranode:latest
          cd ${{ matrix.test_config.test_dir }} && \
          go test -v -run "^${{ matrix.test_config.test_suite }}$/${{ matrix.test_config.test_func }}$" -tags ${{ matrix.test_config.test_tags }}
        env:
          test_dir: ${{ matrix.test_config.test_dir }}
          test_tags: ${{ matrix.test_config.test_tags }}
          settings_context: ${{ matrix.test_config.settings_context || '' }}
          report_name: ${{ matrix.test_config.report_name }}
          GITHUB_ACTIONS: true
        continue-on-error: false

      # - name: Publish Test Summary Results
      #   run: npx github-actions-ctrf ${{ matrix.test_config.report_name }}
