name: nightly-test-runs
on:
  schedule:
    - cron: "0 0 * * *" # Runs at midnight UTC every day
  workflow_dispatch:

env:
  REPO: ubsv
  ECR_REGION: eu-north-1
  SETTINGS_CONTEXT_DEFAULT: "default_context"

jobs:
  run-tests:
    runs-on: ubsv-runner
    strategy:
      matrix:
        test_config:
          - test_dir: "test/tnc"
            test_tags: "test_tnc"
            report_name: "test-tnc-report.json"
          - test_dir: "test/tnb"
            test_tags: "test_tnb"
            report_name: "test-tnb-report.json"
          - test_dir: "test/tnf"
            test_tags: "test_tnf"
            report_name: "test-tnf-report.json"
          - test_dir: "test/tnj"
            test_tags: "test_tnj"
            report_name: "test-tnj-report.json"
          - test_dir: "test/tna"
            test_tags: "test_tna"
            report_name: "test-tna-report.json"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.ECR_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - uses: actions/setup-go@v5
        with:
          go-version: "1.21.0"
          cache: "false"

      - name: Build Docker Image
        run: docker compose -f docker-compose.e2etest.yml build

      - name: Run Tests
        run: |
          make install-tools
          cd ${{ matrix.test_config.test_dir }} && \
          go test -v -tags ${{ matrix.test_config.test_tags }} -json | \
          go-ctrf-json-reporter -output ../../${{ matrix.test_config.report_name }} --verbose
        env:
          test_dir: ${{ matrix.test_config.test_dir }}
          test_tags: ${{ matrix.test_config.test_tags }}
          settings_context: ${{ matrix.test_config.settings_context || '' }}
          report_name: ${{ matrix.test_config.report_name }}
          GITHUB_ACTIONS: true
        continue-on-error: false

      - name: Publish Test Summary Results
        run: npx github-actions-ctrf ${{ matrix.test_config.report_name }}
