name: golangci-lint
on:
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  golangci:
    name: lint
    runs-on: ubsv-runner
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21.0'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v5
        with:
          only-new-issues: true
          version: latest
