name: sonar-scan
on:
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  sonarqube:
    name: Sonarqube
    runs-on: ubsv-runner
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Disabling shallow clones is recommended for improving the relevancy of reporting
          fetch-depth: 0

      - uses: twingate/github-action@v1
        with:
          service-key: ${{ secrets.TWINGATE_GH_ACTIONS_SERVICE_KEY }} # Required

      - name: Run Go tests
        run: make longtests
        continue-on-error: true

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v2.0.1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarqube.ubsv.dev
