on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: version
        id: version
        uses: flatherskevin/semver-action@8a609a1edbf89f62b2a2ebad6e183d089240c4cc
        with:
          incrementLevel: patch
          source: tags
      - name: check version
        run: echo next version is ${{ steps.version.outputs.nextVersion }}
