---
name: teranode-public
on:
  push:
    # tags:
    #   - 'release-v*'
    branches:
      - teranode_public_repo

env:
  ECR_REGION: eu-north-1
  SOURCE_REPO: ubsv
  DEST_REPO: teranode-public


jobs:
  # Pull/push image for X86 (AMD64)
  pull_push_amd64:
    uses: ./.github/workflows/teranode_public_pull_push.yaml
    secrets: inherit
    with:
      arch: amd64
      tag: latest-amd64
      region: eu-north-1
      src_repo: ubsv
      dest_repo: teranode-public
  # Pull/push image for ARM64 (Graviton and Darwin)
  pull_push_arm64:
    uses: ./.github/workflows/teranode_public_pull_push.yaml
    secrets: inherit
    with:
      arch: amd64
      tag: latest-amd64
      region: eu-north-1
      src_repo: ubsv
      dest_repo: teranode-public
  # Create docker manifest for multiple architecture tags
  create_manifest:
    needs: [pull_push_amd64, pull_push_arm64]
    uses: ./.github/workflows/teranode_public_manifest.yaml
    secrets: inherit
    with:
      region: eu-north-1
      repo: teranode-public
      tag: latest
