name: Teranode main pull request test build

on:
  pull_request:

permissions:
  contents: read
  pull-requests: read
  id-token: write

env:
  SETTINGS_CONTEXT_DEFAULT: test

jobs:
  # Tests and code lint
  test_and_lint:
    uses: ./.github/workflows/teranode_pr_tests.yaml
    secrets: inherit
