---
name: teranode-public
on:
  push:
    tags:
      - 'release-v*'

env:
  REF_NAME: ${{ github.ref_name }}

jobs:

  # Pull/push image for X86 (AMD64)
  pull_push_amd64:
    uses: ./.github/workflows/teranode_public_pull_push.yaml
    secrets: inherit
    with:
      arch: amd64
      region: eu-north-1
      src_repo: teranode
      dest_repo: teranode-public

  # Pull/push image for ARM64 (Graviton and Darwin)
  pull_push_arm64:
    uses: ./.github/workflows/teranode_public_pull_push.yaml
    secrets: inherit
    with:
      arch: arm64
      region: eu-north-1
      src_repo: teranode
      dest_repo: teranode-public

  # Isolate version from release tag
  isolate_version:
    runs-on: ubuntu-latest
    outputs:
      version_tag: ${{ steps.get_tag.outputs.version_tag }}
    steps:
      - name: Separate version from release tag
        id: get_tag
        run: |
          echo "version_tag=$(echo $REF_NAME | sed 's/release-//')" >> $GITHUB_OUTPUT

  # Create docker manifest for multiple architecture tags
  create_manifest:
    needs:
      - pull_push_amd64
      - pull_push_arm64
      - isolate_version
    uses: ./.github/workflows/teranode_public_manifest.yaml
    secrets: inherit
    with:
      region: eu-north-1
      repo: teranode-public
      version_tag: ${{ needs.isolate_version.outputs.version_tag }}
