name: teranode-public-manifest
on:
  workflow_call:
    inputs:
      repo:
        description: 'Repo name'
        required: true
        type: string
      region:
        description: 'AWS region'
        required: true
        type: string
      version_tag:
        description: 'Release version'
        required: true
        type: string

permissions:
  contents: read
  pull-requests: read
  id-token: write

jobs:
  build_manifest:
    name: Build manifest
    runs-on: ubuntu-latest
    outputs:
      registry: ${{ steps.login-ecr.outputs.registry }}
    steps:

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
          aws-region: ${{ inputs.region }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: true

      - uses: int128/docker-manifest-create-action@v2
        with:
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/${{ inputs.repo }}:latest
            ${{ steps.login-ecr.outputs.registry }}/${{ inputs.repo }}:${{ inputs.version_tag }}
            ${{ steps.login-ecr.outputs.registry }}/${{ inputs.repo }}:${{ github.sha }}
          sources: |
            ${{ steps.login-ecr.outputs.registry }}/${{ inputs.repo }}:${{ github.sha }}-amd64
            ${{ steps.login-ecr.outputs.registry }}/${{ inputs.repo }}:${{ github.sha }}-arm64
