name: Teranode main test build push

on:
  push:
    tags:
      - 'v*'
    branches:
      - main
      - staging
      - release/*

permissions:
  contents: read
  pull-requests: read
  id-token: write

jobs:
  # Tests and code lint
  test_and_lint:
    uses: ./.github/workflows/teranode_main_tests.yaml
    secrets: inherit

  # Run remote build and deploy workflow
  build-and-deploy:
    uses: bitcoin-sv/.github/.github/workflows/build_and_deploy.yaml@main
    permissions:
      contents: read
      packages: write
      id-token: write
    with:
      repository: ${{ github.repository }}
      tag_latest: true
      build_args: |
        DEBUG=true
      use_packages: true
      use_ecr: true
      ecr_region: "eu-north-1"
      ecr_repo: "teranode"
      architectures: '["amd64", "arm64"]'
      runner_labels: '{"amd64":"teranode-runner","arm64":"teranode-runner-arm","manifest":"ubuntu-latest"}'
    secrets: inherit

  # Run chain integrity test
  chainintegrity:
    needs: build-and-deploy
    #uses: ./.github/workflows/chainintegrity-3blasters.yaml
    uses: ./.github/workflows/chainintegrity.yaml
    permissions:
      contents: read
      pull-requests: read
      id-token: write
      packages: read
    secrets: inherit
