name: Teranode main pull request tests

on:
  workflow_call

permissions:
  contents: read
  pull-requests: read
  id-token: write

env:
  REPO: teranode
  ECR_REGION: eu-north-1
  SETTINGS_CONTEXT_DEFAULT: test
  GO_VERSION: '1.24.5'

jobs:
  golangci:
    name: lint
    runs-on: arc-runners
    container:
      image: public.ecr.aws/i7l4o1l2/teranode-github-runner:amd64
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: false

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          only-new-issues: true
          args: -j $(nproc) --timeout=5m

  test:
    name: test
    runs-on: arc-runners
    container:
      image: public.ecr.aws/i7l4o1l2/teranode-github-runner:amd64
    steps:
      - uses: actions/checkout@v4

      # Set up AWS CLI
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
          aws-region: ${{ env.ECR_REGION }}

      # Authenticate Docker to AWS ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: true

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: false

      - name: Run Go tests
        run: CGO_ENABLED=1 make -j$(nproc) test
        continue-on-error: false

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.out
          retention-days: 1
      # - name: Publish Test Summary Results
      #   if: always()
      #   run: npx github-actions-ctrf ctrf-report.json

  smoketest:
    name: smoketest
    runs-on: arc-runners
    container:
      image: public.ecr.aws/i7l4o1l2/teranode-github-runner:amd64
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.ECR_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: true

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: "false"

      - name: Run Smoke tests
        run: make smoketest
        continue-on-error: false
        env:
          settings_context: ${{ env.SETTINGS_CONTEXT_DEFAULT }}


  sonarqube:
    name: Sonarqube
    runs-on: arc-runners
    container:
      image: public.ecr.aws/i7l4o1l2/teranode-github-runner:amd64
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: coverage-report

      - name: Run filename check script
        run: |
          ./scripts/check_filenames.sh

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: false

      # Re-run golangci-lint separately without exiting on errors and generating a report for use in Sonar
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          args: -j $(nproc) --timeout=5m --issues-exit-code=0 --output.checkstyle.path=golangci-lint-report.xml

      # Disabled on self hosted runners in EKS because we're creating twingate sidecar container for every job run
      # - uses: twingate/github-action@v1.5
      #   with:
      #     service-key: ${{ secrets.TWINGATE_SELF_HOSTED_RUNNERS }}
      #   continue-on-error: true

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarqube.prod.ubsv.dev

      - name: SonarQube Quality Gate check
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 10
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarqube.prod.ubsv.dev
