name: Teranode main pull request test build

on:
  pull_request:

permissions:
  contents: read
  pull-requests: read
  id-token: write

env:
  SETTINGS_CONTEXT_DEFAULT: test

jobs:
  # Tests and code lint
  test_and_lint:
    uses: ./.github/workflows/teranode_pr_tests.yaml
    secrets: inherit

  # Run remote build and deploy workflow
  build-and-deploy:
    uses: bitcoin-sv/.github/.github/workflows/build_and_deploy.yaml@main
    permissions:
      contents: read
      packages: write
      id-token: write
    with:
      repository: ${{ github.repository }}
      tag_latest: false
      build_args: |
        DEBUG=true
      use_packages: true
      use_ecr: true
      ecr_region: "eu-north-1"
      ecr_repo: "teranode"
      architectures: '["amd64", "arm64"]'
      runner_labels: '{"amd64":"teranode-runner","arm64":"teranode-runner-arm","manifest":"ubuntu-latest"}'
    secrets: inherit
    
  # Run chain integrity test
  chainintegrity:
    needs: build-and-deploy
    uses: ./.github/workflows/chainintegrity-3blasters.yaml
    permissions:
      contents: read
      pull-requests: read
      id-token: write
      packages: read
    secrets: inherit
