name: Build and Deploy remote test

on:
  workflow_dispatch:

jobs:
  get_repo_name:
    runs-on: ubuntu-latest
    env:
      REPO: ${{ github.repository }}
    outputs:
      repo: ${{ steps.ecr_repo.outputs.repo }}
    steps:
      - name: Get ECR repo name from GH repo name
        id: ecr_repo
        run: echo "repo=${REPO##*/}" >> $GITHUB_OUTPUT

  # Run remote build and deploy workflow
  build-and-deploy:
    uses: bitcoin-sv/.github/.github/workflows/build_and_deploy.yaml@main
    needs: [ get_repo_name ]
    with:
      repository: ${{ github.repository }}
      # is_pull_request: ${{ github.event_name == 'pull_request' }}
      is_pull_request: true
      # Optional parameters with their defaults if you want to override them
      use_packages: true
      use_ecr: true
      ecr_region: "eu-north-1"  # Specify your AWS region
      ecr_repo: ${{ needs.get_repo_name.outputs.repo }}
      architectures: '["amd64", "arm64"]'
      runner_labels: '{"amd64":"teranode-runner","arm64":"teranode-runner-arm","manifest":"ubuntu-latest"}'
    secrets: inherit  # Pass all secrets from the calling workflow to the called workflow
